### ISSUE TITLE
Define the namespace for the UCO ontology. 

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#103]
This is an issue that needs to be decided upon for the July 12th release of version 0.3.0 (June CASE Workshop action items)

UCO clean-up (July 12, 2019)
I.	Namespaces for CASE (and UCO)
     A.	Base URI(s), Version, Hash or Slash? 
             1.	Ryan H, Sean B, Ryan G, and Vik

**Comment by sbarnum** [comment]
Agreement on call today was that pre-1.0 the namespaces would be structured as follows:

https://unifiedcyberontology.org/ontology/core#UcoObject

Post 1.0 we will possibly incorporate some kind of version identifier but many issues still need to be discussed to have consensus on the right approach.

For now, all namespaces across uco ontology ttl files will need the"ontology/" inserted

**Comment by rhohimer** [comment]
I agree that that was the structure we agreed upon. The actual URI for the UCO ontology was not agreed upon in today's meeting. I'm hoping for a consensus on the following, or something very similar:

https://unifiedcyberontology.org/ontology/uco/uco#

Which in turn would import:
https://unifiedcyberontology.org/ontology/uco/core#
https://unifiedcyberontology.org/ontology/uco/observable#
https://unifiedcyberontology.org/ontology/uco/types#
https://unifiedcyberontology.org/ontology/uco/action#
https://unifiedcyberontology.org/ontology/uco/identify#
https://unifiedcyberontology.org/ontology/uco/investigation#
https://unifiedcyberontology.org/ontology/uco/location#
https://unifiedcyberontology.org/ontology/uco/pattern#
https://unifiedcyberontology.org/ontology/uco/role#
https://unifiedcyberontology.org/ontology/uco/tool#
https://unifiedcyberontology.org/ontology/uco/victim#

Then, the CASE ontology  can import the  https://unifiedcyberontology.org/ontology/uco/uco# to get access to all.

**Comment by rhohimer** [comment]
The topic of namespaces and URIs is controversial and at times heated. I have my opinions, much like all of the others do. Some people like Fords, others Chevys. But if I want to get somewhere, the make of the car is of lesser importance than getting in and going.
![image](https://user-images.githubusercontent.com/9854293/61093928-94ce9580-a401-11e9-9d02-3f05acd33537.png)

**Comment by sbarnum** [comment]
Let's talk about the concept and approach of namespacing outside of this ticket and keep this ticket focused on what is needed to change in the current namespaces to be ready for v0.3.0

**Comment by packet-rat** [comment]
Ryan & Sean,

A "Hatlo Tip of the Hat"  to both of you for working your way through these topics and advancing our game!

Let's us know if you need the community to chip and "get you a room" ;-)


Pat Maroney




On Jul 12, 2019, at 11:49 AM, Sean Barnum <notifications@github.com> wrote:

Let's talk about the concept and approach of namespacing outside of this ticket and keep this ticket focused on what is needed to change in the current namespaces to be ready for v0.3.0

**Comment by sbarnum** [comment]
I am going to create a branch/PR with "ontology/uco/" added to the namespaces and "http" changed to "https"

**Comment by sbarnum** [comment]
Addressed in PR #124

**Comment by sbarnum** [comment]
Resolved in PR #124
