### ISSUE TITLE
Recent merges have introduced class errors with respect to Authorization, AlternateDataStream, WindowRegistryValue, WindowsPESection, and EnvironmentVariable. 

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#112]
These are due to recent changes and I should have been more rigorous in reviewing the merge.

![image](https://user-images.githubusercontent.com/9854293/60917399-bbe06800-a245-11e9-9e13-75ec9a825fc0.png)

**Comment by rhohimer** [comment]
observable:hashes has a range of types:ArrayOfHash 
The class definition for AlternateDataStream conflicts with this definition:
AternateDataStream subclassOf (hashes max 1 owl:Thing)
should be hashes max 1 ArrayOfHash

**Comment by ajnelson-nist** [comment]
That `AlternateDataStream` clash...actually, whole definition...is strange.  No relation to `UcoObject`?  No `contentData`?  Does `AlternateDataStream` pertain to the NTFS feature, or to something else?

**Comment by sbarnum** [comment]
The observable:hashes issue should be fixed according to the solution of issue #114

**Comment by sbarnum** [comment]
@ajnelson-nist 
To clarify the structured use of AlternateDataStream, yes it is pertaining to the NTFS feature.

In UCO there is an NTFSFileSystem facet(property bundle) defined which is intended to be added onto a CyberItem (Trace) UcoObject.
One of its properties is observable:alternateDataStreams which is an ObjectProperty with range observable:AlternateDataStream.
Currently the model only defines the hashes, size and name properties on AlternateDataStream as far as I can see. This could certainly be added to if necessary/appropriate.

Hopefully, this clears it up a little.

**Comment by sbarnum** [comment]
@rhohimer 
We will require more information on the exact nature of the errors asserted above before they can be investigated and resolved if appropriate.

**Comment by sbarnum** [comment]
maybe it is because I simply modified the restrictions for core:name on those classes without explicitly adding domain assertions for each?

**Comment by rhohimer** [comment]
It is likely assertions that do not match range restrictions... such as object properties pointing to owl:Thing instead of the declared range.

**Comment by ajnelson-nist** [comment]
@sbarnum This helps, thank you!  I'm now convinced there needs to be a `:contentData` property, not a `:hashes` property.  This is also the kind of thing that will show up as a called-out `case:Trace`, so IMO `alternateDataStream` needs to also subclass ... either `core:UcoObject`---selfishly, to fit the `case:Trace` inheritance hierarchy---or `observable:CyberItem`, which feels more appropriate in strictly UCO space.

**Comment by sbarnum** [comment]
@ajnelson-nist 
So, this is getting much more complex and off topic from the focus of this ticket.
If you are suggesting such more substantial modifications to UCO could you please create a new issue ticket and explain what you are looking for? Thanks

**Comment by ajnelson-nist** [comment]
@sbarnum 
Agreed, I've expanded the discussion scope.  I'll refocus this into another ticket tomorrow.  I don't think this needs to block 0.3.0.

**Comment by rhohimer** [comment]
I'm discovering other syntactical issues... core.ttl has not been loading in my ontology editor. I'm not going to open another issue unless I clearly see these errors are unrelated.

![image](https://user-images.githubusercontent.com/9854293/61007465-c2441200-a321-11e9-802c-e9557d15eee1.png)

**Comment by rhohimer** [comment]
![image](https://user-images.githubusercontent.com/9854293/61008236-e0ab0d00-a323-11e9-9fbd-e5452733e8fe.png)

Still running this down.

**Comment by rhohimer** [comment]
There was a syntax error in core.ttl on line 283... a duplicate range statement. I'll create a new Issue, Then commit the fix.

**Comment by rhohimer** [comment]
ObjectProperty assertions are in error... causing the Error classes to be formed...
![image](https://user-images.githubusercontent.com/9854293/61010809-b0b43780-a32c-11e9-9559-e514b42e142d.png)

**Comment by rhohimer** [comment]
![image](https://user-images.githubusercontent.com/9854293/61066078-c28fec00-a3b9-11e9-91f6-b3c84d4b5807.png)

Finally making some progress at finding the Error class declarations.

**Comment by rhohimer** [comment]
![image](https://user-images.githubusercontent.com/9854293/61067459-6bd7e180-a3bc-11e9-9062-99457a959352.png)

**Comment by rhohimer** [comment]
![image](https://user-images.githubusercontent.com/9854293/61067847-6b8c1600-a3bd-11e9-840e-6a991b54e311.png)

**Comment by sbarnum** [comment]
so, in that last pic it looks like the onClass and the two someValuesFrom lines just need removed.
Would you agree?

**Comment by rhohimer** [comment]
Yes, still chasing down the all the range issues...
I have everything loading except EnclosingCompliation
There are many range assertions (such as "id" that are set wrong. But that is not part of this issue...

**Comment by sbarnum** [comment]
not sure what you are showing in the pic two comments up.
as far as I can see id prop is handled correctly and I don't think anything regarding it was touched recently.
Can you point to where any specific issue exists?

**Comment by rhohimer** [comment]
Yes, the changes I have made so far are visible in the diffs from master in my local branch... mostly in core.ttl

**Comment by sbarnum** [comment]
hmm, does not look like core imports types. Maybe that is the issue? Though that is nothing new.

**Comment by rhohimer** [comment]
![image](https://user-images.githubusercontent.com/9854293/61070155-d12ed100-a3c2-11e9-8856-39e0ce3332d1.png)

**Comment by sbarnum** [comment]
LOL. No, I don't think that was supposed to be MaxCardinality of 0 for either name or description.

And, yes the range of name should be string not the domain. LOL

How in the world?

**Comment by rhohimer** [comment]
![image](https://user-images.githubusercontent.com/9854293/61082011-6939b400-a3dd-11e9-9142-ea111332cdf2.png)
Still tracking stuff down...

**Comment by rhohimer** [comment]
![image](https://user-images.githubusercontent.com/9854293/61087877-be7cc200-a3eb-11e9-80b6-cd551e8e5e33.png)
 Woo hoo!

**Comment by sbarnum** [comment]
Resolved in PR #117
