### ISSUE TITLE
marking.ttl is not loading... 

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#118]
![image](https://user-images.githubusercontent.com/9854293/61089016-a0fd2780-a3ee-11e9-9773-d7823ca8f93b.png)

I'm not sure what is causing this. Looks like syntax errors????

**Comment by rhohimer** [comment]
![image](https://user-images.githubusercontent.com/9854293/61089178-2e407c00-a3ef-11e9-842f-8c1775070074.png)

Hoping it is this simple...

**Comment by sbarnum** [comment]
Resolved in PR #119
