### ISSUE TITLE
New logical errors in ReleaseToMarking and MessageThread

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#128]
![image](https://user-images.githubusercontent.com/9854293/61152651-e0368180-a49d-11e9-9f40-e13cb6e438a5.png)

Found a couple of newly introduced logical errors.

![image](https://user-images.githubusercontent.com/9854293/61152742-183dc480-a49e-11e9-858f-8bd89c0ab88a.png)

**Comment by sbarnum** [comment]
hmmm. ReleaseToMarking is very simple and almost identical to LicenseMarking and StatementMarking which apparently work?

**Comment by sbarnum** [comment]
I found the issue on messagethread.

I did not change the owl:onDataRange to owl:onClass when I modified the range of the restriction for :message

**Comment by sbarnum** [comment]
Resolved in PR #130
