### ISSUE TITLE
Typo correction - "sSpecifies"

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#140]
I noticed a documentation typo.  Pull Request coming in a minute.

**Comment by rhohimer** [comment]
What's the status on this? @ajnelson-nist are you still submitting a Pull Request?
The typo is still present:
```
observable:processorArchitecture
	a owl:DatatypeProperty ;
	rdfs:label "processorArchitecture"@en ;
	rdfs:comment "sSpecifies the specific architecture (e.g. x86) used by the CPU of the system."@en ;
	rdfs:range xsd:string ;
	.
```

**Comment by ajnelson-nist** [comment]
Since PR 142 was merged into the `v0.4.0-dev` branch, it looks like this issue can be closed.  Is policy to close issues when merged into the `develop` branch (in this case, `v0.4.0-dev`), or merged into `master`?

**Comment by rhohimer** [comment]
My feeling is that when a PR is merged into the current dev branch that it can be closed. Otherwise the Change Log gets very messy. This is something that should be ironed out in our operations discussion.

**Comment by ajnelson-nist** [comment]
Agreed.  I'll close now.  Thank you.
