### ISSUE TITLE
Casing correction - "picturetype"

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#143]
I noticed `observable:picturetype` is inconsistently cased compared with neighboring properties.  Pull request coming in a minute.

**Comment by sbarnum** [comment]
I agree. This looks like an error

**Comment by ajnelson-nist** [comment]
I'm not sure why I pushed out a patch for this, but then didn't issue a Pull Request.  I've issued the Pull Request.

**Comment by ajnelson-nist** [comment]
Oh, I think I just forgot to issue the PR after feedback was provided.

**Comment by sbarnum** [comment]
Addressed in commit c5fb551738a1420a70df5d844c6467691e9d16af

**Comment by sbarnum** [comment]
Fixed in https://github.com/ucoProject/UCO/releases/tag/0.4.0
