### ISSUE TITLE
Modularize Domain Assertions - Related to  Issue #104

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#147]
See issue #104 
The current uco ontology has used the domain settings on ObjectProperty and DataProperty in such a way that it is incompatible with applications that wish to use domain settings axioms for inferencing.

This issue can be addressed by modularizing the domain axioms assertions to a separate ontology and namespace.  Instead of asserting the domain axioms in the same namespace as the property, the suggested solution is to assert the domain axioms in a separate ontology and namespace. This allows users that wish to use the UCO ontology with the domain axioms to include the domain-assertions namespace and use the ontology with the domain assertions. On the other hand, if the user does not wish to use the domain axioms, they simply do not import the domain-assertions ontology.

@rhohimer and @HamptonJ are prototyping this solution to determine if modularization (using a separate ontology for domain assertions) will work.

If the solution proves to be useful, we will submit the branch for review.

**Comment by rhohimer** [comment]
Just pushed the prototype branch into the repository:  **### domain-assertions-modularization**

The domain assertions from observable.ttl have been moved to domain-assertions.ttl and placed in their own namespace.

**Comment by rhohimer** [comment]
In the process of working on modularizing domain settings I found that actionStatus does not have domain or range settings.
![image](https://user-images.githubusercontent.com/9854293/61583737-0341e080-aaf1-11e9-8447-74dcc008241a.png)

**Comment by rhohimer** [comment]
Just committed and pushed the domain-assertions-modularization branch. The domain assertions that were in action.ttl have been moved to domain-assertions.ttl

**Comment by rhohimer** [comment]
autorizationType has no domain or range set
![image](https://user-images.githubusercontent.com/9854293/61585173-989d9e80-ab0a-11e9-9baa-ae3ef1ab5f66.png)

**Comment by rhohimer** [comment]
While working on moving core.ttl domain assertions I saw this warning:
![image](https://user-images.githubusercontent.com/9854293/61585341-f41d5b80-ab0d-11e9-921d-6b7624375a0b.png)

**Comment by rhohimer** [comment]
A new branch has been created that resolves this issue by separating the domain assertions into separte ontology files.

**Comment by rhohimer** [comment]
I referenced the issue number in the branch. Therefore I reopened the issue so that background information is available.

**Comment by packet-rat** [comment]
Confirming this is now in :"https://github.com/ucoProject/UCO/tree/issue-147-reh-v0.4.0-dev-separated-domain-assertions"  vs.  **domain-assertions-modularization** branch as stated earlier?

**Comment by sbarnum** [comment]
Addressed in c36115b93e7f1d3f819b4424f481ba089d7340ce

**Comment by sbarnum** [comment]
Fixed in https://github.com/ucoProject/UCO/releases/tag/0.4.0
