### ISSUE TITLE
Lost track of Time. Check to make sure that the time.ttl is included in the uco.ttl master.

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#148]
While working on prototyping a case.ttl I noticed that the uco.ttl did not include the time.ttl. There is not much to the time.ttl. But we shouldn't waste the time we have.

**Comment by packet-rat** [comment]
Are you REALLY ready to engage on Temporality?  

Caution before retorting - this presumes an equal commitment to dealing with Causality!

“We’ll be waiting for your answer.  The decision is up to you.”   
              The Day the Earth Stood Still.

Patrick Maroney


On Jul 24, 2019, at 9:57 AM, Ryan Hohimer <notifications@github.com> wrote:

While working on prototyping a case.ttl I noticed that the uco.ttl did not include the time.ttl. There is not much to the time.ttl. But we shouldn't waste the time we have.

**Comment by rhohimer** [comment]
@packet-rat We can address temporality... when the time is right.....


By denying scientific principles, one may maintain any paradox.
 - Galileo Galilei

**Comment by sbarnum** [comment]
Addressed in commit 78aa4f1cda884d6f6b3a4a9b4a93d0851272b4b0

**Comment by sbarnum** [comment]
Fixed in https://github.com/ucoProject/UCO/releases/tag/0.4.0
