### ISSUE TITLE
There is an illegal redeclaration of the "core:id" property. It is declared as both an ObjectProperty and a DataProperty. 

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#150]
This is what we have referred to as a Punning issue. DataProperties and ObjectProperties should have unique names.

This error is in the core.ttl file.

**Comment by sbarnum** [comment]
I do not see any punning issue on core:id.

Please provide more specific detail.

**Comment by sbarnum** [comment]
Cannot find this issue.
