### ISSUE TITLE
More illegal redeclarations of entities found.

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#151]
action:actionStatus
investigation:authorizationType
investigation:investigationForm
investigation:investigationStatus

and oddly... 

types:Identifier   (I say oddly because this is a class not a property)

![image](https://user-images.githubusercontent.com/9854293/61819975-f848c200-ae08-11e9-8b55-4512d2556567.png)

**Comment by sbarnum** [comment]
I do not see any punning issue for types:Identifier.
Please provide more specific detail.

All of the rest of these are being flagged as punning because they currently have range <https://unifiedcyberontology.org/ontology/uco/core#ControlledVocabulary>

Once Issue #75 is resolved these errors will go away.

**Comment by sbarnum** [comment]
Ryan, could you look into this again and see if you are still seeing issues?

**Comment by rhohimer** [comment]
Yes, I’ll look into it again.

Ryan E. Hohimer
CTO
DarkLight
Mobile: (509) 430-6890
710 George Washington Way, Suite A
Richland, Washington  99352

Email:  ryan@darklight.ai<mailto:ryan@darklight.ai>
www.darklight.ai<http://www.darklight.ai/>
[cid:image001.png@01D5F854.D76E5090]
This e-mail (including any attachments) may contain information that is private, confidential, or protected by attorney-client or other privilege. If you received this e-mail in error, please delete it from your system without copying it and notify sender by reply e-mail so our records can be corrected.

**Comment by rhohimer** [comment]
Yes, It is still an issue... I've have to dig into it.

![image](https://user-images.githubusercontent.com/9854293/76654495-4ccfb780-6528-11ea-8ffd-cbda2e74f503.png)

**Comment by rhohimer** [comment]
There seems to be Annotation properties that are being cast as data properties.
 WARN  12:35:02  Annotation property domain axiom turned to data property domain after parsing. This could introduce errors if the original domain was an anonymous expression: https://unifiedcyberontology.org/ontology/uco/observable#WhoIs is the new domain.

I'm chasing it down now.

**Comment by rhohimer** [comment]
Interesting: This is a WARNING, not an ERROR. I do not think these warnings are of concern.
When we used a separate file to explicitly assert the the Domain axioms, Protege considered them as annotation property domain assertions. So, because the domain assertions were made in a different file than the class definitions Protege warns that it may be a problem. It's not.

 WARN  12:35:02  Annotation property domain axiom turned to data property domain after parsing. This could introduce errors if the original domain was an anonymous expression: https://unifiedcyberontology.org/ontology/uco/observable#WhoIs is the new domain.

This issue can be closed.
