### ISSUE TITLE
OWL file needed?

### ISSUE THREAD

**Issue by RANGERBEE** [ucoProject/UCO#152]
Hello folks,

  Wondering if I am missing something as I peruse the files and readme. Where is the OWL file?

I just came over from the other repo: https://github.com/Ebiquity/Unified-Cybersecurity-Ontology

There is an OWL file there.

Thank you!

**Comment by rhohimer** [comment]
RangerBee,
This repository is a different effort from the Ebiquity effort and repository. We have the same goal of supporting the cybersecurity, digital forensic, and intel communities with semantic interoperability (information integration)
The ontologies in this repository are persisted in the Turtle format (.ttl)

The Turtle files can be easily converted to OWL files. This UCO community wished to work in the turtle format for human readability reasons. However, I convert these files to OWL so my company (DarkLight Inc.) can use them in our inferencing engines in our AI.

If you have questions about the ontologies here, or how to convert them to OWL, I'd be happy to help.
Ryan Hohimer
ryan@darklight.ai

**Comment by RANGERBEE** [comment]
@rhohimer ,

  Thank you so much for the bit of clarity. Fully understand at this point and will recognize both repos as disconnected entities. Will do my best to import the TTL files into Protege to meet my goals.

Nice job on DarkLight. 

Thanks again.

**Comment by rhohimer** [comment]
This issue has been resolved. Closing the issue.
