### ISSUE TITLE
Change Proposal: Need to specify subtypes of CyberItem

### ISSUE THREAD

**Issue by sbarnum** [ucoProject/UCO#156]
[UCO-CP-CyberItem-Subclassing-2019-11-19.docx](https://github.com/ucoProject/UCO/files/3866606/UCO-CP-CyberItem-Subclassing-2019-11-19.docx)
Currently ALL observables are expressed as instances of CyberItem with an undefined set of Facets on them. This has been frequently referred to as Duck Typing where you "know" what kind of CyberItem (aka observable) it is by which Facets it has. While this sort of implicit interpretation is useful and adequate for some use cases, other (typically more common) use cases require a more explicit categorization of CyberItem (observable) type.

We need to provide a solution within UCO that maintains support for duck typing while also enabling support for more explicit CyberItem subtyping.

Propose the following:
- First, add specification for two new classes GenericCyberItem and TypedCyberItem (abstract) as subclasses of CyberItem. Duck typing could then use GenericCyberItem and explicitly typed observables could use a set of type classes derived from TypedCyberItem.
- Identify the set and structure of TypedCyberItem subtypes to be defined from the current expressive coverage within UCO v0.3.0 observable.ttl
- Identify the set and structure of additional TypedCyberItem subtypes that need to be defined beyond the current expressive coverage within UCO v0.3.0 observable.ttl
- Add the new subtypes to UCO
- Identify relevant common patterns between the newly defined subtypes and various facets
- Specify appropriate constraints or axioms to convey the identified patterns

**Comment by rhohimer** [comment]
The GenericCyberItem class may not add value in my opinion. How does a GenericCyberItem differ from a CyberItem?  
Also, there is no construct in OWL for a class being abstract. Abstract classes are only definable in programming languages. The open world assumption in ontologies is contradictory to the notion of an abstract class contract.

**Comment by rhohimer** [comment]
This Issue should be accompanied by a Change Proposal. Either Sean or I (Ryan) will complete the UCO Change Proposal form and attach it to this issue.

**Comment by rhohimer** [comment]
I attached a UCO Change Proposal form to the origin issue.

**Comment by rhohimer** [comment]
This is a Change Propsal that has significant impact to UCO. 
It is extremely important to some current adopters of UCO. Therefore, it should be advanced through the process. 
![image](https://user-images.githubusercontent.com/9854293/69683400-907dde80-1069-11ea-98cb-927316709caa.png).
Accordingly, it is now open for comment from members of the UCO Ontology Committee, for a period of ten business days.
Given the holiday of November 28 & 29, that puts the minimum comment period open until December 12th.

**Comment by sbarnum** [comment]
Covered under JIRA OC-65: https://unifiedcyberontology.atlassian.net/browse/OC-65
and CP-13: https://unifiedcyberontology.atlassian.net/wiki/spaces/OC/pages/688029697/UCO+CP-13+ObservableObject+subclasses
