### ISSUE TITLE
Add a new Observation class to observable.ttl

### ISSUE THREAD

**Issue by sbarnum** [ucoProject/UCO#157]
Add a new Observation class to observable.ttl where 
- Observation is a subclass of Action
- core:name="observe"
- the observables that were observed during the observation are expressed in the action:object property
- the identity, tool, software (etc.) that made the observation is expressed in the action:performer property
- any tool or other instrument used to make the observation is expressed in the action:instrument property
- the time at which the observation occurred is expressed in the startTime and endTime properties

This will make it explicitly clear how to convey observations and do so in a manner which is consistent with the rest of UCO.

**Comment by sbarnum** [comment]
Potential solution in branch Issue-157-sdb

**Comment by ajnelson-nist** [comment]
What distinguishes the usage of this from an `InvestigativeAction`?

**Comment by rhohimer** [comment]
This is from my viewpoint as a cybersecurity operations person. Continuous monitoring is done for indicators of security issues. Continuous monitoring is a matter of making regular observations. An observation of an indicator of compromise may indeed trigger and investigation. That investigation may in turn lead to InvestigativeAction.

In short: Observations are not all within the context of an investigation.

**Comment by ajnelson-nist** [comment]
That helps me out.  Thank you!

**Comment by ehazard-mitre** [comment]
This issue has been changed to "committed" due to the merge of PR #172 into branch _develop_. It's now staged for merging into master (for 0.4.0 release).

**Comment by sbarnum** [comment]
Fixed in https://github.com/ucoProject/UCO/releases/tag/0.4.0
