### ISSUE TITLE
Add modifiedTime, objectStatus, lang & metadata properties to UCOObject

### ISSUE THREAD

**Issue by sbarnum** [ucoProject/UCO#158]
The UCOObject class is currently missing some key properties to enable its practical real-word use.

To support practical versioning of objects as they evolve and change, propose the addition of the following new property as required on UCOObject:
core:modifiedTime
a owl:DatatypeProperty
rdfs:comment """Specifies the time that this particular version of the object was modified. The object creator can use the time it deems most appropriate as the time this version of the object was modified. The value of the modified property for a given object version MUST be later than or equal to the value of the created property.
Object creators MUST update the modified property when creating a new version of an object.
The modified timestamp MUST be precise to the nearest millisecond (exactly three digits after the decimal place in seconds)."""@en-US ;
rdfs:range xsd:dateTime

To support tracking of status for particular objects as they are codified, exchanged, persisted, analyzed, etc., propose the addition of the following new property as required on UCOObject:
core:objectStatus
a owl:DatatypeProperty
rdfs:comment "Specifies the current status of the object."@en-US ;
rdfs:range vocab:ObjectStatusVocab

vocab:ObjectStatusVocab with the following values:
active, deprecated, incomplete, draft, unstable, stable, revoked

To support basic explicit tagging of multilingual content, propose the addition of the following new property as optional on UCOObject:
core:lang
a owl:DatatypeProperty
rdfs:comment """Specifies the language of the text content in this object. When present, it MUST be a language code conformant to RFC 5646. If the property is not present, then the language of the content is unspecified."""@en-US ;
rdfs:range vocab:ISO639LangaugeCodeVocab

vocab:ISO639LangaugeCodeVocab with the ISO 639-1 language codes (e.g., "en-us")

To support the codification of object characteristics that are undefined in UCO (e.g., ad-hoc characteristics), propose the addition of the following new property as optional on UCOObject:
core:metadata
a owl:DatatypeProperty
rdfs:comment "Specifies a reference to characteristic metadata, as key/value pairs, for an entity. The value portion of any entry may be one and only one of the following: a single literal, a set of literals, a referenced UCO Object, a set of referenced UCO Objects, an embedded dictionary, a set of embedded dictionaries"@en-US
rdfs:range core:DictionaryEntry

New class core:DictionaryEntry
a owl:Class ;
rdfs:comment """Specifies the name and corresponding value for an entry within a dictionary.
One of key_value or dictionary or object properties MUST exist, but MUST exist independent of the others."""@en-US ;
rdfs:subClassOf owl:Thing ;
  rdfs:subClassOf [
      a owl:Restriction ;
      owl:cardinality "1"^^xsd:nonNegativeInteger ;
      owl:onProperty core:key_name ;
    ] ;
  rdfs:subClassOf [
      a owl:Restriction ;
      owl:minCardinality "0"^^xsd:nonNegativeInteger ;
      owl:onProperty core:key_value ;
    ] ;
  rdfs:subClassOf [
      a owl:Restriction ;
      owl:minCardinality "0"^^xsd:nonNegativeInteger ;
      owl:onProperty core:object ;
    ] ;
  rdfs:subClassOf [
      a owl:Restriction ;
      owl:minCardinality "0"^^xsd:nonNegativeInteger ;
      owl:onProperty core:dictionary ;
    ] ;
.

core:keyName
a owl:DatatypeProperty
rdfs:comment "Specifies the name of the key for the metadata entry."@en-US ;
rdfs:range xsd:string ;

core:keyValue
a owl:DatatypeProperty
rdfs:comment """Specifies the value associated with the key name for the metadata entry is a string or list of strings, an integer, or a timestamp in UTC format. 
If the keyValue is specified, the keyName property MUST be used but the dictionary and object properties MUST NOT be specified."""@en-US ;
  rdfs:range [
      a owl:Class ;
      owl:unionOf (
          xsd:string
          xsd:int
          xsd:dateTime
          xsd:boolean
        ) ;
    ] ;

core:dictionary
a owl:DatatypeProperty
rdfs:comment "Specifies a nested dictionary.
If a nested dictionary is to be used, the keyName property MUST be used but the keyValue and object properties MUST NOT be specified."@en-US ;
rdfs:range core:DictionaryEntry

**Comment by packet-rat** [comment]
Food for thought:  it’s not hard to imagine near term scenarios where machines vs. humans are creating objects.  Does time-stamp precision reflect events in machine time-scales?

Pat Maroney


> On Nov 26, 2019, at 3:17 PM, Sean Barnum <notifications@github.com> wrote:
> 

﻿
The UCOObject class is currently missing some key properties to enable its practical real-word use.

To support practical versioning of objects as they evolve and change, propose the addition of the following new property as required on UCOObject:
core:modifiedTime
a owl:DatatypeProperty
rdfs:comment """Specifies the time that this particular version of the object was modified. The object creator can use the time it deems most appropriate as the time this version of the object was modified. The value of the modified property for a given object version MUST be later than or equal to the value of the created property.
Object creators MUST update the modified property when creating a new version of an object.
The modified timestamp MUST be precise to the nearest millisecond (exactly three digits after the decimal place in seconds)."""@en-us ;
rdfs:range xsd:dateTime

To support tracking of status for particular objects as they are codified, exchanged, persisted, analyzed, etc., propose the addition of the following new property as required on UCOObject:
core:objectStatus
a owl:DatatypeProperty
rdfs:comment "Specifies the current status of the object."@en-us ;
rdfs:range vocab:ObjectStatusVocab

vocab:ObjectStatusVocab with the following values:
active, deprecated, incomplete, draft, unstable, stable, revoked

To support basic explicit tagging of multilingual content, propose the addition of the following new property as optional on UCOObject:
core:lang
a owl:DatatypeProperty
rdfs:comment """Specifies the language of the text content in this object. When present, it MUST be a language code conformant to RFC 5646. If the property is not present, then the language of the content is unspecified."""@en-us ;
rdfs:range vocab:ISO639LangaugeCodeVocab

vocab:ISO639LangaugeCodeVocab with the ISO 639-1 language codes (e.g., "en-us")

To support the codification of object characteristics that are undefined in UCO (e.g., ad-hoc characteristics), propose the addition of the following new property as optional on UCOObject:
core:metadata
a owl:DatatypeProperty
rdfs:comment "Specifies a reference to characteristic metadata, as key/value pairs, for an entity. The value portion of any entry may be one and only one of the following: a single literal, a set of literals, a referenced UCO Object, a set of referenced UCO Objects, an embedded dictionary, a set of embedded dictionaries"@en-us
rdfs:range core:DictionaryEntry

New class core:DictionaryEntry
a owl:Class ;
rdfs:comment """Specifies the name and corresponding value for an entry within a dictionary.
One of key_value or dictionary or object properties MUST exist, but MUST exist independent of the others."""@en-us ;
rdfs:subClassOf owl:Thing ;
  rdfs:subClassOf [
      a owl:Restriction ;
      owl:cardinality "1"^^xsd:nonNegativeInteger ;
      owl:onProperty core:key_name ;
    ] ;
rdfs:subClassOf [
      a owl:Restriction ;
      owl:minCardinality "0"^^xsd:nonNegativeInteger ;
      owl:onProperty core:key_value ;
    ] ;
rdfs:subClassOf [
      a owl:Restriction ;
      owl:minCardinality "0"^^xsd:nonNegativeInteger ;
      owl:onProperty core:object ;
    ] ;
rdfs:subClassOf [
      a owl:Restriction ;
      owl:minCardinality "0"^^xsd:nonNegativeInteger ;
      owl:onProperty core:dictionary ;
    ] ;
.

core:keyName
a owl:DatatypeProperty
rdfs:comment "Specifies the name of the key for the metadata entry."@en-us ;
rdfs:range xsd:string ;

core:keyValue
a owl:DatatypeProperty
rdfs:comment """Specifies the value associated with the key name for the metadata entry is a string or list of strings, an integer, or a timestamp in UTC format. 
If the keyValue is specified, the keyName property MUST be used but the dictionary and object properties MUST NOT be specified."""@en-us ;
  rdfs:range [
      a owl:Class ;
      owl:unionOf (
          xsd:string
xsd:int
          xsd:dateTime
          xsd:boolean
        ) ;
    ] ;

core:dictionary
a owl:DatatypeProperty
rdfs:comment "Specifies a nested dictionary.
If a nested dictionary is to be used, the keyName property MUST be used but the keyValue and object properties MUST NOT be specified."@en-us ;
rdfs:range core:DictionaryEntry

**Comment by sbarnum** [comment]
This issue was broken out into separate issues for each of its 4 constituent parts.
As such, this issue is now being closed.
