### ISSUE TITLE
Change Proposal: Revise range and documentation of partitionID

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#160]
This proposal adjusts the `observable:partitionID` property after inspection of some sample data.

Proposal:
[UCO-CP-partitionID-revision-2020-01-02.docx](https://github.com/ucoProject/UCO/files/4017431/UCO-CP-partitionID-revision-2020-01-02.docx)

**Comment by rhohimer** [comment]
@ajnelson-nist Thanks for submitting this Change Proposal. Please consider this as an official recognition of receipt of the change proposal.

**Comment by sbarnum** [comment]
Addressed in 64f01944fe03cf46e7a23f8767b698b54cb55288

**Comment by ajnelson-nist** [comment]
Thank you for merging this.

**Comment by ajnelson-nist** [comment]
Oh, sorry, I forgot I'd suggested in the change proposal that some information be added to a migration guide.  And I think we've all been forgetting to keep a change log.

**Comment by sbarnum** [comment]
Fixed in https://github.com/ucoProject/UCO/releases/tag/0.4.0
