### ISSUE TITLE
Errors and Warnings are thrown when loading the current develop branch into Protege

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#179]
There are multiple errors and warnings that should be addressed. Attached is the Protege log file disclosing the problems. 

[protege-log-uco-develop.txt](https://github.com/ucoProject/UCO/files/4416465/protege-log-uco-develop.txt)

Some are "acceptable" warnings, but the failures to load ontologies  and the unparsible triples are not acceptable.

**Comment by rhohimer** [comment]
Yesterday, I agreed to look into this issue. I don't have an estimation of when the issue will be resolved. 
It appears to be related to the refactoring of Enumerations to Vocabularies.

**Comment by rhohimer** [comment]
The it is the core.ttl that is failing to load. I suspect at this time that it is because of an error in vocabulary.ttl. This is a new addition to the core.ttl. Additionally, many of the warnings in the log are about parsing errors in vocabulary.ttl

**Comment by rhohimer** [comment]
The core.ttl ontology was not loading due to syntax errors. Thanks, to Paul Patrick for finding them.
Correcting the core.ttl syntax errors allows the ontology to load. However, there are still unparsed triples. Meaning the vocabularies are not usable (valid) yet. Many INFO warnings when loading vocabulary.ttl

Level:       INFO
Time:        1587771445880
Message:     Unparsed triple: https://unifiedcyberontology.org/ontology/uco/vocabulary#TaskActionTypeVocab -> http://www.w3.org/2002/07/owl#onDatatype -> http://www.w3.org/2001/XMLSchema#string


I'm still working the issue...

**Comment by rhohimer** [comment]
![image](https://user-images.githubusercontent.com/9854293/80282137-96cdc080-86c4-11ea-92ac-9ab6b42e5a7d.png)
The above datatype definition in vocabulary.ttl causes theses errors and warnings:
![image](https://user-images.githubusercontent.com/9854293/80282173-d7c5d500-86c4-11ea-9508-054a02b6ccee.png)

This is just one of the vocabularies defined in vocabulary.ttl.  I can fix the syntax, but since I am not the original author, I may not accomplish the intent. In other words, I may swap a syntax error for an intent error.

**Comment by rhohimer** [comment]
@sbarnum I have been able to correct the syntax in the above declaration of an enumeration of strings. However, I do not believe I have accomplished the intent of what you are trying to accomplish.

I don't understand the self-referential oneOf statement. Since I am not sure my changes to the one declaration are what you intended I'm not going to make the changes to all the vocabularies you are trying to define.

I'll push to the origin a branch with the corrected, core.ttl.  And pass the assignment back to you for   getting vocabulary.ttl to conform to your intent.

**Comment by rhohimer** [comment]
@sbarnum I pushed to origin a branch called: develop-04-24-2020-core-changes

This branch corrects the syntax errors in core.ttl

However, it does not have any changes to vocabulary.ttl.  owl:onDatarype xsd:string ; statement are throwing unparsed triple errors. Passing the baton back to you.

**Comment by sbarnum** [comment]
@rhohimer Thank you for the branch with the core.ttl syntax error fixes. Could you please issue a PR for that so I can approve and merge it into develop?

Also, on the vocabulary issue you are seeing I am unclear on what the underlying issue is.
I know that the exact syntax used is what is used at FireEye and works fine there.
I spoke with Paul about it and together we spent a good chunk of time trying to figure out what issues may exist. Each of us visually could not discern any issues. We then ran vocabulary.ttl through TopBraid, EasyRDF, and a few other RDF validation tools and all of them parsed it cleanly with no errors or even informational warnings. 
You mention above that you have found a way to correct the syntax and make your INFO warnings go away. Could you please share what the exact changes you made so that we can evaluate whether they adhere to or violate the intent and to determine if this is truly an RDF/OWL issue or a Protege issue given that it looks like Protege may be the only tool complaining? Just looking for more context to move forward.
Thanks again.

**Comment by rhohimer** [comment]
@sbarnum  You can make the Pull Request for core just as easy as me, and it is your code. However, you can just make separate commits of the syntax changes in core.ttl into the pull request with the vocabulary.ttl changes.

https://user-images.githubusercontent.com/9854293/80282173-d7c5d500-86c4-11ea-9508-054a02b6ccee.png

I was able to create this vocabularies as Literal Enumerations. Its seems to me that you are trying to  allow a data range of more than Literals, hence the "Cannot translate list item to an individual..." warning.

If this is what your intent is you'll probably need to expand the DataRange to include both Individuals and Literals.
If these are just warnings, and not errors, then a unit test to verify that the intended purpose is met and the code works should be made. Does a semantic graph accept and retrieve data expressed with these vocabulary definitions? If so, I think that is acceptable, if not, we need to figure out how to get the intended behavior working.

![image](https://user-images.githubusercontent.com/9854293/80311354-18d8ea80-8794-11ea-95d5-495ff04dad64.png)

**Comment by rhohimer** [comment]
@sbarnum and @ajnelson-nist   I just normalized vocabulary.ttl and then opened it. The fatal errors are missing. So, it would be good to go except the import of editor-annotation is still there (which I would be willing to remove) and all the edt:typeIdentifier "myvocab-ov" statements are still there (which I don't have time to remove today). 

Unless, @ajnelson-nist addressed this is the import and statements in the Issue 178-ajn-inclusion-postponement branch? 

 Please advise.

**Comment by rhohimer** [comment]
@sbarnum and @ajnelson-nist   yes... Alex removed the edt import and statements... nice.  However, in that branch the owl:onDatatype xsd:string ; statements still exist. :-( 

So, to get through with this... I'll go ahead and make the necessary edits to develop, renormalize, and make a PR assigning @sbarnum and @ajnelson-nist as reviewers

**Comment by rhohimer** [comment]
I've made the corrections, normalized, tested for fatal errors, and pushed a branch to the origin. I'll create the pull request now.

**Comment by sbarnum** [comment]
Fixed in https://github.com/ucoProject/UCO/releases/tag/0.4.0
