### ISSUE TITLE
Domain assertion of observable:displayName is too restrictive

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#184]
`observable:displayName` is a property of the facets `DigitalAccount`, `EmailAddress`, and `WindowsService`.  A domain assertion in today's `develop` head unnecessarily restricts `displayName` to belonging to `WindowsService`.

The domain assertion should either be expanded or removed.

**Comment by ajnelson-nist** [comment]
I stumbled on this while aligning the CASE example `accounts.json` with UCO 0.3.0. This is also true for today's state of `develop`.

**Comment by sbarnum** [comment]
This issue will be addressed through implementation of
JIRA OC-68: https://unifiedcyberontology.atlassian.net/browse/OC-68
and CP-13: https://unifiedcyberontology.atlassian.net/wiki/spaces/OC/pages/984678401/UCO+CP-23+Convert+current+property+restrictions+and+domain+assertions+to+SHACL+shapes
