### ISSUE TITLE
Remove the core:role domain assertion from the core-da.ttl file

### ISSUE THREAD

**Issue by CourtneyHass** [ucoProject/UCO#186]
When loaded in protege the class RelatedIdentity is being created.

**Comment by sbarnum** [comment]
This issue will be addressed through implementation of
JIRA OC-68: https://unifiedcyberontology.atlassian.net/browse/OC-68
and CP-13: https://unifiedcyberontology.atlassian.net/wiki/spaces/OC/pages/984678401/UCO+CP-23+Convert+current+property+restrictions+and+domain+assertions+to+SHACL+shapes
