### ISSUE TITLE
createdTime has ambiguous appearances

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#187]
This Issue arose on at least two occasions while working on CASE development.  It arose once a few weeks ago, while a group I was in was working on mapping concepts to existing definitions; and once as I was updating CASE's "Asgard" website example.

The property `createdTime` has two occurrences in UCO:
* `core:createdTime` is a property of a `UcoObject`, and appears to be meant to record the time of the instantiation of the `UcoObject` by the data modeler.  That is, if the same subject data were analyzed by two different processes, one would expect this property *to not match* between data mappings into a UCO-based graph (barring miraculously synchronized clocks).
* `observable:createdTime` is a property of many classes in the Observable namespace, and seems to be a representation of data (such as the file system "creation"/"birth" timestamp type).  That is, if the same subject data were analyzed by two different processes, one would expect this property *to match* between data mappings into a UCO-based graph.

These are quite different in conceptual and usage scope.  Namespacing and property-domain attachment alone were not enough to save that first group I was working with a few minutes scratching our heads at the difference.

I request *at least* that these two properties of matching names be related to one another, with usage explanations similar to what I provided above, with refinements to their documenting `rdfs:comment` strings.  I believe it would ultimately be better for the two properties to have different names.  I will be happy to write a change proposal on hearing how extensive a change the CASE and UCO communities would be comfortable with.

**Comment by ajnelson-nist** [comment]
For reference, the Trace where I came across this today is on this page, under "Step 3", "Network Traffic".
https://caseontology.org/ontology/examples.html

**Comment by packet-rat** [comment]
Make case 1: instantiationTime (or something discriminatory).  Seems like different ‘things’ should have different names if they represent different concepts?


Patrick Maroney


On Apr 22, 2020, at 2:20 PM, Alex Nelson <notifications@github.com> wrote:

﻿
For reference, the Trace where I came across this today is on this page, under "Step 3", "Network Traffic".
https://caseontology.org/ontology/examples.html

**Comment by rhohimer** [comment]
This is very frequently encountered in continuous monitoring. There are different "times" involved. When an event occurs, when it is logged, when it is read, when it is transferred, when it is modified,  when it is "instantiated" in an analytic system, etc.  In my opinion, there should be different property names for each unique concept.

namespaces are for protecting us from variable name collisions, not for disambiguation purposes, again, my opinion.

**Comment by sbarnum** [comment]
Covered under JIRA OC-54: https://unifiedcyberontology.atlassian.net/browse/OC-54
and CP-25: https://unifiedcyberontology.atlassian.net/wiki/spaces/OC/pages/1011318789/UCO+CP-25+Modify+definition+of+observable+createdTime+to+disambiguate+it+from+core+createdTime
