### ISSUE TITLE
observable:sizeInBytes has inconsistent range

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#188]
The `sizeInBytes` property appears in two facets, `File` and `ContentData`.  The property's definition gives it the range `xsd:long`, as does the range constraint in `ContentData`.  However, `File` specifies it is an `xsd:integer`.  I suggest this be `xsd:long` on `File` as well.

**Comment by ajnelson-nist** [comment]
This is being addressed in UCO's Jira, OC-19, CP-24.

**Comment by sbarnum** [comment]
Covered by CP-24: https://unifiedcyberontology.atlassian.net/wiki/spaces/OC/pages/1005879308/UCO+CP-24+Modify+all+integer-based+DatatypeProperties+with+a+range+of+xsd+long+to+have+a+range+of+xsd+integer
