### ISSUE TITLE
Is this domain specification correct?

### ISSUE THREAD

**Issue by panosprotopapas** [ucoProject/UCO#209]
Hello and apologies for perhaps a silly-non issue and/or use of wrong terminology.

In https://github.com/ucoProject/UCO/blob/master/uco-core/core-da.ttl#L53 is it correct to define `core:endTime`, `rdfs:domain`, `investigation:Authorization` ? Shouldn't `investigation:Authorization` `rdfs:subClassOf` `<core-class>`, and then `<core-class>` include `core:endTime` in its domain?

**Comment by ajnelson-nist** [comment]
Thanks, @panosprotopapas .  That is a clear bug, because of semantics and because the investigation file went away in UCO 0.5.0.  The -da files are close to being replaced, so we might or might not spot-fix this one.

**Comment by panosprotopapas** [comment]
Ah I see, thanks for your answer @ajnelson-nist . Feel free to close this if you wish.

**Comment by ajnelson-nist** [comment]
The fix might be non-trivial.  This is currently being tracked in UCO Jira Bug OC-83.

**Comment by panosprotopapas** [comment]
Closing this since it's tracked in UCO Jira Bug OC-83
