### ISSUE TITLE
Representing Recoverability of Unallocated Files

### ISSUE THREAD

**Issue by cyberinvestigationexpress** [ucoProject/UCO#251]
Implement 2018 approved CASE change proposal that is listed on caseontology.org website:

https://caseontology.org/resources/references/Representing%20Recoverability%20of%20Unallocated%20Files%20using%20CASE%20UCO%2031Jan2018.pdf

See UCO CP-43 - Representing Recoverability of Unallocated Files

**Comment by ajnelson-nist** [comment]
This is being tracked in [OC-119](https://unifiedcyberontology.atlassian.net/browse/OC-119).

**Comment by cyberinvestigationexpress** [comment]
Transfer UCO CP-43 Representing Recoverability of Unallocated/Unavailable Files to https://github.com/ucoProject/UCO/tree/Feature-CP-43

**Comment by cyberinvestigationexpress** [comment]
Submitted pull request to resolve this issue and satisfy requirements in CP-43

**Comment by cyberinvestigationexpress** [comment]
Transcribed CP43 examples to https://github.com/casework/CASE-Examples/tree/uco-issue-251/examples/illustrations/recoverability

**Comment by eoghanscasey** [comment]
Discussing with @ajnelson-nist we decided that RecoveredObjectFacet is a more suitable name for this. I am making edits to PR in preparation for Solution vote.
