### ISSUE TITLE
Add properties to Android device

### ISSUE THREAD

**Issue by cyberinvestigationexpress** [ucoProject/UCO#253]
(UCO CP-50) Add properties to Android device to represent information captured by tools

**Comment by ajnelson-nist** [comment]
This is being tracked in [OC-122](https://unifiedcyberontology.atlassian.net/browse/OC-122).

**Comment by ajnelson-nist** [comment]
This proposal was added to UCO 0.8.0.  The resulting page is [here](https://drive.google.com/file/d/15R0z_i2wt325tKRClCtcuq-bswU2kavx/view).
