### ISSUE TITLE
Need a context-specific property bundle for Inode properties

### ISSUE THREAD

**Issue by sbarnum** [ucoProject/UCO#3]

**Comment by ajnelson-nist** [comment]
To help understand the in-common properties: How will a modification timestamp be represented between an inode and an MFT entry?  (And a FAT directory entry?)

**Comment by sbarnum** [comment]
From Eoghan Casey:

**extInode**
Attribute Range Comment
extInodeID xsd:integer
extFileType xsd:integer
extDeletionTime xsd:dateTimeStamp
extInodeChangeTime xsd:dateTimeStamp
extPermissions xsd:integer
extSGID xsd:integer
extSUID xsd:integer
extFlags xsd:integer
extHardLinkCount xsd:integer
**extDirectBlock List of pointers to 12 blocks Represent as ContentData related to extInode**
extIndirectBlock xsd:integer Location of block of pointers
extDoubleIndirectBlock xsd:integer Location of block of pointers
extTripleIndirectBlock xsd:integer Location of block of pointers
(leave ext4 to next version)

**Comment by sbarnum** [comment]
Just to ensure I am understanding what you are proposing for the bolded elements, the following is my interpretation (none of the bolded properties would exist natively within the outlined PBs but would rather be expressed on Relationships):

- For extDirectBlock
    - I am a little confused on what exactly is being proposed here. It looks like it is being proposed to just treat the set of 12 direct block pointers as a chunk-o-data with a ContentData section in a separate trace. And treat the three indirect block pointer properties as simple single values.
    - Potential concerns: 
        - no way to easily break out each of the direct block pointers
        - no way to characterize the blocks of pointers pointed to by the indirect block pointers
        - is it not forensically relevant to fully capture and characterize these details or am I overthinking it?



- Suggested potential alternative for extDirectBlock:
    - Create a new supporting class called ExtIndirectBlockReference
        - ExtIndirectBlockReference (details of a single EXT indirect block pointer including the actual pointer value itself and an index reference to an ExtInodePointerBlock PB characterizing the block of pointers that this indirect pointer points to)
            - extIndirectBlockPointer : integer (0..1) (the actual direct pointer to the indirect pointer block)
            - extIndirectBlockIndex : string (0..1) (the index identifier for the indirect ExtInodePointerBlock PB instance on the same single object (Trace))
    -Create another new property bundle called ExtInodePointerBlock
        - ExtInodePointerBlock
            - index : string (1) (an index identifier for this ExtInodePointerBlock instance) (MUST be unique within single object (Trace))
            - directPointers : integer (0..*) (list of direct pointers to blocks of file data)
            - indirectPointers : ExtIndirectBlockReference (0..*) (list of indirect block references (actual pointers and index references to ExtInodePointerBlock PBs on the same single object (Trace)))
    - Utilize the following properties within the extInode PB
        - ExtInode
            - extDirectBlockIndex : string (0..1) (the index identifier for the direct ExtInodePointerBlock PB instance on the same single object (Trace))
            - extIndirectBlock : ExtIndirectBlockReference (0..1) (single indirect block reference (actual pointer and index reference to ExtInodePointerBlock PB on the same single object (Trace)))
            - extDoubleIndirectBlock : ExtIndirectBlockReference (0..1) (double indirect block reference (actual pointer and index reference to ExtInodePointerBlock PB on the same single object (Trace)))
            - extTripleIndirectBlock : ExtIndirectBlockReference (0..1) (triple indirect block reference (actual pointer and index reference to ExtInodePointerBlock PB on the same single object (Trace)))
    - The above design is targeted to be fully expressive and as flat/simple as possible
    - Usage:
        - To convey an NTFS file with no block pointers
            - Create Trace
            - Add ExtInode PB
                - Do not specify any values for extDirectBlockIndex, extIndirectBlock, extDoubleIndirectBlock, and extTripleIndirectBlock properties
        - To convey an NTFS file with a set of direct block pointers but no indirect pointers:
            - Create Trace
            - Add ExtInode PB
                - Assign extDirectBlockIndex property a unique value
            - Add ExtInodePointerBlock PB
                - Specify “index” property equal to the extDirectBlockIndex value assigned above
                - Specify list of direct block pointers in the “directPointers” property
        - To convey an NTFS file with a set of direct block pointers and an indirect pointer
            - Create Trace
                - Add ExtInode PB
                    - Assign extDirectBlockIndex property a unique value
                    - Set extIndirectBlock property with a unique value for extIndirectBlockIndex and with the actual indirect pointer value in the extIndirectBlockPointer property
            - Add ExtInodePointerBlock PB (this will be the content of the direct block pointers in the file)
                - Specify “index” property equal to the extDirectBlockIndex value assigned above
                - Specify list of direct block pointers in the “directPointers” property
            - Add ExtInodePointerBlock PB (this will be the content of the block of direct block pointers that is pointed to by the indirect pointer)
                - Specify “index” property equal to the extIndirectBlockIndex value assigned above
                - Specify list of direct block pointers in the “directPointers” property
        - To convey an NTFS  file with a double indirect pointer
            - Create Trace
                - Add ExtInode PB
                    - Set extDoubleIndirectBlock property with a unique value for extIndirectBlockIndex and with the actual indirect pointer value in the extIndirectBlockPointer property 
            - Add ExtInodePointerBlock PB (this will be the content of the block of indirect block pointers that is pointed to by the double indirect pointer)
                - Specify “index” property equal to the extIndirectBlockIndex value assigned above
                - Specify list of indirect block pointers/indexes in the “indirectPointers” property
            - Add ExtInodePointerBlock PB (one for each indirect pointer block specified in the 
                - Specify “index” property equal to the extIndirectBlockIndex value assigned in the “indirectPointers” property above
                - Specify list of direct block pointers in the “directPointers” property

Example
[EXT-block-pointers.json.txt](https://github.com/ucoProject/uco-1.0-draft/files/634882/EXT-block-pointers.json.txt)

**Comment by ajnelson-nist** [comment]
From discussion on our phone call this morning, we think the direct and indirect block properties are not necessary for draft 1.

**Comment by ajnelson-nist** [comment]
For reference, [here](https://github.com/torvalds/linux/blob/master/fs/ext2/ext2.h#L300) is the `struct ext_inode` definition in the Linux kernel.

**Comment by sbarnum** [comment]
Sean, Alex and Harm concurred that Sean's alternate approach described above is likely overkill and not necessary.

**Comment by ajnelson-nist** [comment]
Oddly enough, the ext2 header has a comment calling ctime "creation time," which disagrees with the Carrier File System Forensics book (table 15.10), and the [ext4 header](https://github.com/torvalds/linux/blob/master/fs/ext4/ext4.h#L708).

**Comment by ajnelson-nist** [comment]
I'm fine with this property list in the third Issue comment, less the block pointers.

**Comment by ajnelson-nist** [comment]
Follow-up to the direct/indirect block properties:

On the call, we discussed the merits of including information in CASE that could be used to identify the provenience of file content addresses -- which is basically meta-provenience.  We were unable to imagine someone would want to run queries across CASE for this level of file system forensics (which Harm correctly raised is different from file forensics).

**Comment by sbarnum** [comment]
This issue has been addressed and solution exists in observable.ttl.

I am not sure exactly when it was added.
