### ISSUE TITLE
IMSI and MSISDN Representation

### ISSUE THREAD

**Issue by kchason** [ucoProject/UCO#355]
# Background

Currently, the IMSI and MSISDN properties are associated with a `MobileDeviceFacet` and `SIMCardFacet` respectively. This doesn't allow a concept of either property changing.

# Requirements

**Requirement 1**: `MobileAccountFacet` must house the properties `IMSI` and `MSISDN`.  (Note - it currently does.)
**Requirement 2**: `SimCardFacet` must reference a `MobileAccount` and drop direct storage of the `IMSI` string.
**Requirement 3**: `MobileDeviceFacet` must reference a `MobileAccount` and drop direct storage of the `MSISDN` string.

## Benefits

By relating the properties to a `MobileAccountFacet`, it allows the concept of an IMSI or MSISDN changing within the
same SIMCard or MobileDevice.

## Risks

A change to the existing properties has the risk of breaking the implementation of current adopters.

### Competency 1

# Solution summary

Requirements 2 and 3 also fully describe the solution, implemented in [PR 354](https://github.com/ucoProject/UCO/pull/354).

# Coordination

- Tracking in Jira ticket [OC-224](https://unifiedcyberontology.atlassian.net/browse/OC-224)
- [x] Milestone 1 is resolving [CASE-Examples Issue 53](https://github.com/casework/CASE-Examples/issues/53).  That might be doable right now, or it might require working through the remainder of the present Issue.
- [ ] Transcribe all relevant content from [UCO CP-37](https://unifiedcyberontology.atlassian.net/wiki/spaces/OC/pages/1261109249/UCO+CP-37+represent+phoneNumber+and+IMSI+separately+from+account) into this issue, and archive that Confluence page when finished.
- [ ] Review relevant email thread(s) and apply refreshed understanding to Requirements in this proposal.
- [ ] Requirements to be discussed in Ontology Committee (OC) meeting, date TBD

- [ ] Requirements Review vote has not occurred

- [ ] Solutions Approval to be discussed in OC meeting, date TBD
- [ ] Solutions Approval vote has not occurred

- [ ] Implementation has not been merged into `develop`

**Comment by ajnelson-nist** [comment]
@kchason , one non-obvious change I made in the requirements: you were describing a `Facet`-to-`Facet` property link.  UCO properties will link from a `Facet` to a `UcoObject`, but not from a `Facet` to a `Facet`.  @sbarnum , this is worth description in the design document.

**Comment by ajnelson-nist** [comment]
This proposal has been withdrawn.
