### ISSUE TITLE
Ability to express external identifiers

### ISSUE THREAD

**Issue by sbarnum** [ucoProject/UCO#38]
It would be useful to be able to convey external (non-UCO) identifiers for any UcoObject.
This property would need to have cardinality 0..* and each entry would at a minimum consist of the a property for the identifier itself and a property to convey the context of the identifier.
This could be done as a native property of UcoObject or could simply be defined as a facet/property-bundle.

For example, something like the following as a native property:
```json
{
  "@id": "identity-a5b2df87-bc86-491d-837c-0dc18e4b6f15",
  "@type": "Identity",
  "name": "AT&T Inc.",
  "externalID": [
    {
      "@type": "ExternalId",
      "externalIDValue": "18",
      "externalIDContext": "NSRLMfgCode"
    }
  ]
}
```

OR something like the following as a facet/property-bundle:
```json
{
  "@id": "identity-a5b2df87-bc86-491d-837c-0dc18e4b6f15",
  "@type": "Identity",
  "name": "AT&T Inc.",
  "facet": [
    {
      "@type": "ExternalId",
      "externalIDValue": "18",
      "externalIDContext": "NSRLMfgCode"
    }
  ]
}
```

**Comment by sbarnum** [comment]
What likely makes more sense is to potentially change the ExternalReference object in uco-core to derive from Facet rather than UcoObject.
As such it can simply be attached as a facet/property-bundle to any UcoObject.

So, the above facet/property-bundle example would look something like:
```json
{
  "@id": "identity-a5b2df87-bc86-491d-837c-0dc18e4b6f15",
  "@type": "Identity",
  "name": "AT&T Inc.",
  "facet": [
    {
      "@type": "ExternalReference",
      "externalIdentifier": "18",
      "definingContext": "NSRLMfgCode"
    }
  ]
}
```

This would also involve minimal changes to the v0.1.0 model/ontology.

The key difference is that you would no longer be able to characterize an external reference as an independent object and relate it to other objects. It would become a property of a single object.
If you had a situation where a single external reference/identifier were relevant to numerous objects you would have to add the property bundle to each object rather than defining it as a separate object and defining a relationship between it and each object or a single relationship between it and all of the relevant objects.

**Comment by ajnelson-nist** [comment]
I think I understand this use case, but need some confirmation.  Is this for when an RDF IRI is not available?

I think this has a few holes yet.  How is a schema referenced?  How would a string external identifier be handled versus an integer identifier?

**Comment by sbarnum** [comment]
Fixed in https://github.com/ucoProject/UCO/releases/tag/0.4.0
