### ISSUE TITLE
Newb Questions

### ISSUE THREAD

**Issue by packet-rat** [ucoProject/UCO#39]
![2017-04-19_17-02-49](https://cloud.githubusercontent.com/assets/3220193/25202204/82cee5ac-2522-11e7-9bee-2a0b46e7efb2.png)

**Comment by sbarnum** [comment]
Everything in red highlight is not valid JSON.
It is there as "comments" to clarify the JSON content for the reader.
Unfortunately, JSON does not have a structure for comments so if you would need to remove the "//" followed by text to make it valid JSON.

There is no difference between the two plugin tool entries with differing comments ("//UFED Plugin" vs "//Plugin").
That is just a typo on my part. :-)

**Comment by packet-rat** [comment]
So many languages...data formats...doh! : "//" is a Comment!!! Who'd a thunk that 🤔

Patrick Maroney
(609)841-5104

On Apr 20, 2017, at 4:44 PM, sbarnum <notifications@github.com> wrote:

Everything in red highlight is not valid JSON.
It is there as "comments" to clarify the JSON content for the reader.
Unfortunately, JSON does not have a structure for comments so if you would need to remove the "//" followed by text to make it valid JSON.

There is no difference between the two plugin tool entries with differing comments ("//UFED Plugin" vs "//Plugin").
That is just a typo on my part. :-)

**Comment by jstroud-mitre** [comment]
@packet-rat @sbarnum  are we okay to close this issue?

**Comment by rhohimer** [comment]
Finally, closing this issue.
