### ISSUE TITLE
Add ConfiguredTool object 

### ISSUE THREAD

**Issue by cyberinvestigationexpress** [ucoProject/UCO#405]
# Background
Need to represent multiple different configurations of the same tool, each referencing the same Tool object. Knowing what tool was run for each different configuration should be represented as a link in the graph, and not rely on the string name value. In addition, tool configuration needs an added property to reference an object that was provided as an argument/input to the Tool (e.g. so you could have a graph-object for NSRL-as-of-March-2022 or ClamAV signature-database version X, and show where in the graph that object had been involved in decision processes).

# Requirements

## Requirement 1

UCO must be able to represent how a tool was configured at the time of its invocation.

## Requirement 2

A tool configuration that uses an object (such as a file or service endpoint) must be representable similar to the literal-valued `tool:itemValue`.

## Requirement 3

UCO must be able to represent that one tool was used under multiple configurations.

## Requirement 4

UCO must be able to use one tool configuration in multiple invocations.

_E.g._ if a tool `analyzer_engine` has a configuration involving calling it on the command line with the flag `--auto-detect-content-type`, and the tool is called once per input file for two input files, those two tool invocations should have their `action:instrument` objects use the same `ConfiguredTool`.

## Requirement 5

UCO must support looking up when a tool is used with a certain flag.

_E.g._ if a tool `analyzer_engine` can take the unparameterized (0-argument) command-line flag `--auto-detect-content-type`, a UCO graph should be reviewable for when `analyzer_engine` is configured to use that flag, and in what `action:Action`s that configuration was used.

## Requirement 6

UCO must support looking up when a tool is used with a certain flag-value.  This applies to object-values (such as a file or service end-point reference), and literal-values (such as a string).

E.g. if a tool `analyzer_engine` can take the parameterized (1-argument) command-line flag `--assume-content-type`, a UCO graph should be reviewable for when `analyzer_engine` is configured to use that flag, and in what `action:Action`s that configuration was used.

## Requirement 7

One tool used in multiple configurations should be linkable between those configurations and the actions using those configurations.

# Risk / Benefit analysis

## Benefits
Permit representation of multiple different configurations of the same tool, while maintaining link to the same Tool 

## Risks
The submitter is unaware of risks associated with this change

# Competencies demonstrated

## Competency 1
When a single tool is used in a workflow with multiple configuration sections, determine which Tool was used to obtain all observables, independent of all different tool configurations used.

### Competency Question 1.1

What Tool was used to obtain all observables?

#### Result 1.1

Query returns a single result Tool.

## Competency 2

A version of a tool known to contain a defect should be locatable within a graph, to understand the impact of results.

### Competency Question 2.1

`analyzer_engine` version 1.0 is known to include a defect that reverses the latitudes and longitudes within JPEG EXIF metadata.  What results, under any configuration of `analyzer_engine`, are affected by this defect?

## Competency 3

When different versions of a resource (e.g., NSRL hashset, AntiVirus database) were provided in various ConfiguredTool objects, determine which resource was provided as an argument to a given ConfiguredTool object.

### Competency Question 3.1

What resource was referenced in the itemObject property of a given ConfiguredTool object?

#### Result 3.1

Query returns a single object that was referenced in the itemObject of the given ConfiguredTool object.

# Solution suggestion
* Add ConfiguredTool object to UCO `tool:` ontology.
* Add uco-tool:itemObject property for use in uco-tool:ConfigurationSettingType to reference an object that was provided as an argument/input to the `ConfiguredTool`.
* Add new irreflexive object-property `tool:isConfigurationOf`, with `rdfs:range tool:Tool`, `rdfs:domain tool:ConfiguredTool`.
   - Unresolved implementation question: Should `isConfigurationOf` be restricted to have a domain that is a `tool:Tool`, but also not a `tool:ConfiguredTool`?  Put another way: can a `ConfiguredTool` be configured further?  The initial implementation will assume it is permissible to permit knowledge representations like this:
```json
{
    "@id": "kb:some-configured-tool-2",
    "tool:isConfigurationOf": {
        "@id": "kb:some-configured-tool-1"
    }
}
```

# Coordination

- Tracking in Jira ticket [OC-115](https://unifiedcyberontology.atlassian.net/browse/OC-115)

- [x] Administrative review completed, proposal announced to Ontology Committees (OCs) on 2022-06-27
- [x] Requirements to be discussed in OC meeting, [2022-06-30](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2021064705/2022-06-30+CDO+Ontology+Committees)
- [x] Requirements Review vote occurred, passing, on 2022-07-11
- [x] *Requirements development phase completed.*
- [x] Solution announced to OCs on 2022-08-15
- [ ] Solutions Approval to be discussed in OC meeting, [2022-08-25](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2036989953/2022-08-25+CDO+Ontology+Committees)
- [ ] Solutions Approval vote has not occurred

- [ ] *Solutions development phase completed.*
- [ ] Implementation has not been merged into `develop`

- [x] Milestone linked
- [ ] Documentation logged in pending release page

**Comment by plbt5** [comment]
@cyberinvestigationexpress Some questions/remarks:

1. In Requirement 1:
    1. It is currently specified as a solution to achieve something, without indicating what that something actually is. Please specify your requirements in terms of what it is that this CP wants to achieve for the user, its functionality, what it is that cannot be achieved in the current version. In fact, the background already describes the requirements in general terms. You might want to further elaborate on its details (the tool (in a particular version?) must be represented as a unique datum, having one (or more?) specific configurations). The background can then address the context of use, and/or its kinds of tools that should be supported. 
    2. Is it the intention to differentiate between a `Tool` and a `ConfiguredTool`? If not, I'd suggest to remove `Configured` from its name. If a distinction does exist, please indicate their distinction as well as how both concepts relate to each other. 
2. About Competency 2:
    1. This uses the terms `resource` and `argument` that have not been introduced before. Do they refer to the same thing, or different things? Is this the same as Tool, or Configuration, or something else? In the current competency description I don't understand the question nor its answer.

**Comment by ajnelson-nist** [comment]
@plbt5 , I'll process most of your replies (I agree with specification of solution being confused with specification of need), as Eoghan and I had both come to roughly the same representation needs, and settled a way forward recently.

In response to your "Difference between `Tool` and `ConfiguredTool` question - it is a question of specialization.  Say I have a command-line tool `analyzer_engine` that has two significant and mutually-exclusive flags, `--auto-detect-content-type`, and `--assume-content-type X`.  I have these questions I would want to answer:

1. What are the results when using `--auto-detect-content-type`?
2. What are the results when using `--assume-content-type X` for `X=foo`?
3. What are the results when using `--assume-content-type X` for `X=bar`?
4. What is the version of the tool used to generate my results?

**Comment by ajnelson-nist** [comment]
@cyberinvestigationexpress , @plbt5 - I have made an in-progress update, revising the issue's initial draft.

R1 was:

> Add ConfiguredTool object to UCO

It is now:

> UCO must be able to represent how a tool was configured at the time of its invocation.

This requirement is already mostly satisfied with `tool:ToolConfigurationTypeFacet`.  However, there is no corresponding `tool:ToolConfiguration` object; nor is it clear if there should be one.


R2 (by copy-paste error, a second R1) was:

> Add uco-tool:itemObject property for use in uco-tool:ConfigurationSettingType to reference an object that was provided as an argument/input to the Tool

It is now:

> A tool configuration that uses an object (such as a file or service endpoint) must be representable similar to the literal-valued `tool:itemValue`.

I've added a new R3--R7, and a third competency.  I need to pause for another meeting.

**Comment by sbarnum** [comment]
I would concur with the outlined Requirements in this proposal but do not think I agree with the proposed solution. Without an example I am unsure I am fully understanding the proposed solution so it is possible that is part of my reticence.

It seems to me that a more effective way to address these requirements would be:

- add the tool:configurationSettings property to tool:ToolConfigurationTypeFacet
  - this would allow instantial configuration details to be specified for a tool using this facet which is the intent of the facet anyway. I believe it is a bug that this property somehow got left off of this facet
- add a tool:itemObject property optionally on tool:ConfigurationSettingType

Using these simple changes, 

1. you can specify the characterization of a tool independent of its instantial usage configuration with a tool:Tool object.
2. you can specify the characterization of a tool specific to its instantial usage configuration with a tool:Tool object containing a tool:ToolConfigurationTypeFacet
  - In a specific action taken at a specific time this approach would be taken
3. you can specify that a configuration-specific tool (number 2 above) is a specific configuration of a configuration-independent tool (number 1 above and relevant to multiple different potential usage configurations and usages) with a simple Relationship with core:kindOfRelationship="Is_Configured_Version_Of"

Example:

```json
{
  "@graph": [
    {
      "@id": "kb:Tool-0b635b9f-bdb8-4492-9b4e-dec6797b82db",
      "@type": "uco-tool:Tool",
      "uco-core:name": "IDA Pro",
      "uco-tool:toolType": "binary code analysis tool",
      "uco-tool:creator": "hex-rays",
      "uco-tool:version": "7.7"
    },

    {
      "@id": "kb:Tool-be707329-48fe-4d5d-84f3-7978ba63869e",
      "@type": "uco-tool:Tool",
      "uco-core:name": "IDA Pro",
      "uco-tool:toolType": "binary code analysis tool",
      "uco-tool:creator": "hex-rays",
      "uco-tool:version": "7.7",
      "uco-core:hasFacet": [
        {
          "@type": "uco-tool:ToolConfigurationTypeFacet",
          "uco-tool:configurationSettings": {
            "@type": "uco-tool:ConfigurationSettingType",
            "uco-tool:itemName": "auto-detect-content-type",
            "uco-tool:itemValue": "true",
            "uco-tool:itemType": "commandline-flag"
          }
        }
      ]
    },
    {
      "@id": "kb:Relationship-f32b41f8-2b33-4f0f-9bb4-3a0a0752e3ec",
      "@type": "uco-core:Relationship",
      "uco-core:source": "kb:Tool-be707329-48fe-4d5d-84f3-7978ba63869e",
      "uco-core:target": "kb:Tool-0b635b9f-bdb8-4492-9b4e-dec6797b82db",
      "uco-core:kindOfRelationship": "Is_Configured_Version_Of"
    },
    {
      "@id": "kb:Action-94446a56-1f78-42e4-a4f4-ec94ad7e9118",
      "@type": "uco-action:Action",
      "uco-core:name": "Reverse engineer software to determine malicious intent",
      "uco-core:startTime": {
        "@type": "xsd:dateTime",
        "@value": "2022-05-12T10:21:00.00Z"
      },
      "uco-core:endTime": {
        "@type": "xsd:dateTime",
        "@value": "2022-05-14T15:58:00.00Z"
      },
      "uco-action:location": {
        "@id": "kb:9b82c2bc-10f7-47b2-81a8-443a9f458440"
      },
      "uco-action:performer": {
        "@id": "kb:Analyst-c1d5f9cc-10cd-4fdb-9570-e9d00e6df6f7"
      },
      "uco-action:instrument": {
        "@id": "kb:Tool-be707329-48fe-4d5d-84f3-7978ba63869e"
      },
      "uco-action:environment": {
        "@id": "kb:Computer-e640f827-1f5b-4e8a-bd89-7afdf2c85caa"
      },
      "uco-action:object": [
        {
          "@id": "kb:Software1-2ef1d3c7-eb2d-470d-89ea-291daed6549b"
        }
      ],
      "uco-action:result": [
        {
          "@id": "kb:ProvenanceRecord-aa90afe6-9069-49bb-8ad8-b05d3f4f143b"
        }
      ]
    },

    {
      "@id": "kb:Tool-f40e2a5f-7fdf-491f-8c87-b4cb766a6377",
      "@type": "uco-tool:Tool",
      "uco-core:name": "IDA Pro",
      "uco-tool:toolType": "binary code analysis tool",
      "uco-tool:creator": "hex-rays",
      "uco-tool:version": "7.7",
      "uco-core:hasFacet": [
        {
          "@type": "uco-tool:ToolConfigurationTypeFacet",
          "uco-tool:configurationSettings": {
            "@type": "uco-tool:ConfigurationSettingType",
            "uco-tool:itemName": "assume-content-type",
            "uco-tool:itemValue": "foo",
            "uco-tool:itemType": "commandline-argument"
          }
        }
      ]
    },
    {
      "@id": "kb:Relationship-fd59e98c-b31c-48c8-adde-07b5358911da",
      "@type": "uco-core:Relationship",
      "uco-core:source": "kb:Tool-f40e2a5f-7fdf-491f-8c87-b4cb766a6377",
      "uco-core:target": "kb:Tool-0b635b9f-bdb8-4492-9b4e-dec6797b82db",
      "uco-core:kindOfRelationship": "Is_Configured_Version_Of"
    },
    {
      "@id": "kb:Action-ce95584e-5065-4287-83fd-81df2ac72180",
      "@type": "uco-action:Action",
      "uco-core:name": "Reverse engineer software to determine malicious intent",
      "uco-core:startTime": {
        "@type": "xsd:dateTime",
        "@value": "2022-05-12T10:21:10.00Z"
      },
      "uco-core:endTime": {
        "@type": "xsd:dateTime",
        "@value": "2022-05-14T15:58:12.00Z"
      },
      "uco-action:location": {
        "@id": "kb:9b82c2bc-10f7-47b2-81a8-443a9f458440"
      },
      "uco-action:performer": {
        "@id": "kb:Analyst-c1d5f9cc-10cd-4fdb-9570-e9d00e6df6f7"
      },
      "uco-action:instrument": {
        "@id": "kb:Tool-f40e2a5f-7fdf-491f-8c87-b4cb766a6377"
      },
      "uco-action:environment": {
        "@id": "kb:Computer-e640f827-1f5b-4e8a-bd89-7afdf2c85caa"
      },
      "uco-action:object": [
        {
          "@id": "kb:Software1-2ef1d3c7-eb2d-470d-89ea-291daed6549b"
        }
      ],
      "uco-action:result": [
        {
          "@id": "kb:ProvenanceRecord-8cf982c3-f6d7-4e11-9acf-d5dcc4390f42"
        }
      ]
    },

    {
      "@id": "kb:Tool-134e3cc0-7f74-4ea2-9ac1-3c447f4f6195",
      "@type": "uco-tool:Tool",
      "uco-core:name": "IDA Pro",
      "uco-tool:toolType": "binary code analysis tool",
      "uco-tool:creator": "hex-rays",
      "uco-tool:version": "7.7",
      "uco-core:hasFacet": [
        {
          "@type": "uco-tool:ToolConfigurationTypeFacet",
          "uco-tool:configurationSettings": {
            "@type": "uco-tool:ConfigurationSettingType",
            "uco-tool:itemName": "ruleset",
            "uco-tool:itemObject": {
                "@id": "kb:File-0fedea11-3c8b-400c-9cdb-593edc146194"
              },
            "uco-tool:itemType": "external-ruleset"
          }
        }
      ]
    },
    {
      "@id": "kb:Relationship-529c3413-9706-489c-ad61-e65c989240f4",
      "@type": "uco-core:Relationship",
      "uco-core:source": "kb:Tool-134e3cc0-7f74-4ea2-9ac1-3c447f4f6195",
      "uco-core:target": "kb:Tool-0b635b9f-bdb8-4492-9b4e-dec6797b82db",
      "uco-core:kindOfRelationship": "Is_Configured_Version_Of"
    },
    {
      "@id": "kb:Action-1a8cd716-c0c6-42d4-955f-19b2b9f0e3e6",
      "@type": "uco-action:Action",
      "uco-core:name": "Reverse engineer software to determine malicious intent",
      "uco-core:startTime": {
        "@type": "xsd:dateTime",
        "@value": "2022-05-12T10:21:10.00Z"
      },
      "uco-core:endTime": {
        "@type": "xsd:dateTime",
        "@value": "2022-05-14T15:58:12.00Z"
      },
      "uco-action:location": {
        "@id": "kb:9b82c2bc-10f7-47b2-81a8-443a9f458440"
      },
      "uco-action:performer": {
        "@id": "kb:Analyst-c1d5f9cc-10cd-4fdb-9570-e9d00e6df6f7"
      },
      "uco-action:instrument": {
        "@id": "kb:Tool-kb:Tool-134e3cc0-7f74-4ea2-9ac1-3c447f4f6195"
      },
      "uco-action:environment": {
        "@id": "kb:Computer-e640f827-1f5b-4e8a-bd89-7afdf2c85caa"
      },
      "uco-action:object": [
        {
          "@id": "kb:Software1-2ef1d3c7-eb2d-470d-89ea-291daed6549b"
        }
      ],
      "uco-action:result": [
        {
          "@id": "kb:ProvenanceRecord-c462c7de-0391-4c88-a17c-1f9607fb0c46"
        }
      ]
    },

    {
      "@id": "kb:Action-5f6d3a6e-99ee-48bc-9a65-a7e0ae5d9fb8",
      "@type": "uco-action:Action",
      "uco-core:name": "Reverse engineer software to determine malicious intent",
      "uco-core:startTime": {
        "@type": "xsd:dateTime",
        "@value": "2022-05-12T10:31:10.00Z"
      },
      "uco-core:endTime": {
        "@type": "xsd:dateTime",
        "@value": "2022-05-14T16:12:12.00Z"
      },
      "uco-action:location": {
        "@id": "kb:9b82c2bc-10f7-47b2-81a8-443a9f458440"
      },
      "uco-action:performer": {
        "@id": "kb:Analyst-c1d5f9cc-10cd-4fdb-9570-e9d00e6df6f7"
      },
      "uco-action:instrument": {
        "@id": "kb:Tool-kb:Tool-134e3cc0-7f74-4ea2-9ac1-3c447f4f6195"
      },
      "uco-action:environment": {
        "@id": "kb:Computer-e640f827-1f5b-4e8a-bd89-7afdf2c85caa"
      },
      "uco-action:object": [
        {
          "@id": "kb:Software2-bec1d8eb-2db1-444d-9175-b3c60ac47410"
        }
      ],
      "uco-action:result": [
        {
          "@id": "kb:ProvenanceRecord-0db01c96-f34f-431a-9aff-e1cc4fac9842"
        }
      ]
    }
  ]
}

```

I believe this example demonstrates support for all 7 requirements and related competencies specified in this CP.

This approach avoids the complexity of a new ConfiguredTool type and a new isConfigurationOf property.


As a general note, we should also remove the "type" string from the class names in this namespace to conform with our naming conventions throughout the rest of UCO.

**Comment by ajnelson-nist** [comment]
@sbarnum , I've transcribed your sketch from the last comment into CASE-Examples, [here](https://github.com/casework/CASE-Examples/blob/master/examples/illustrations/configured_tool/configured_tool.json).

Somebody should implement the competencies of this proposal as SPARQL queries.

**Comment by ajnelson-nist** [comment]
I'd gotten something backwards in my initial sketch of the solution for this proposal:

> Add new irreflexive object-property tool:isConfigurationOf, with rdfs:domain tool:Tool, rdfs:range tool:ConfiguredTool.

I reversed the domain and range on accident.  I'm adjusting the proposal now to word that correctly.

**Comment by ajnelson-nist** [comment]
The implementation for this Issue is in PR 447.  Note that an `sh:xone` ("Exactly one") shape-selector was used to cover these mutually-exclusive cases:

1. The tool configuration is parameterized with a literal-string value.
2. The tool configuration is parameterized with an object reference.
3. The tool configuration is parameterized with a value-less flag (e.g. `--debug`).

I encountered an interesting consequence of over-prescribing constraints, with description and demonstrations linked in [this commit](https://github.com/ucoProject/UCO/pull/447/commits/209f7163519eeb29f5db2df76905195d983a3d47).  The short is, if an `sh:xone` is used, the shapes within it need to be minimal.

**Comment by ajnelson-nist** [comment]
[PR 447](https://github.com/ucoProject/UCO/pull/447) contains a tested Solution for Issue 405.

[Issue 432](https://github.com/ucoProject/UCO/issues/432) *might* be implemented and supersede Issue 405, but if it isn't, Issue 405 will be voted for inclusion in 1.0.0.

**Comment by ajnelson-nist** [comment]
[Issue 432](https://github.com/ucoProject/UCO/issues/432), if approved by vote [Thursday](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2036989953/2022-08-25+CDO+Ontology+Committees), will supersede this Issue.

**Comment by ajnelson-nist** [comment]
Closing as superseded by [Issue 432](https://github.com/ucoProject/UCO/issues/432).
