### ISSUE TITLE
Remove requirement of repeating all property constraints from parent to child classes

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#417]
# Background

As the initial UCO implementation of SHACL was being implemented in [UCO 0.7.0](https://unifiedcyberontology.org/releases/0.7.0/), a tool was incorporated to perform some review of sets of constraints between subclasses.  This Issue will call that tool "[The SHIR codebase](https://github.com/casework/CASE-Utility-SHACL-Inheritance-Reviewer/)" ("**SH**ACL **I**nheritance **R**eview"). In summary, the tool looked at the set of data X that would be accepted by all constraints on a class C, and compared the set of data X' that would be accepted by all constraints on any subclass of C, C'.  If X' was a larger set than X---that is, the constraints of C' would seem to permit more---the tool would report an error in the ontology design between class and subclass.

That tool was initially drafted with an understanding of SHACL that has since grown.  In particular, one implementation pattern has been frequently desired as SHACL has been trialed for the last year: Often, a `sh:PropertyShape` for a subclass C' may be defined that only means to tighten one constraint from the corresponding `sh:PropertyShape` on the parent class C, and not declare anything about other constraints.

Take, e.g.:

```turtle
ex:ClassC
	a
		owl:Class ,
		sh:NodeShape
		;
	sh:property [
		a sh:PropertyShape ;
		sh:class ex:ClassA ;
		sh:maxCount 2 ;
		sh:path ex:propertyP ;
	] ;
	sh:targetClass ex:ClassC ;
	.

ex:ClassD
	a
		owl:Class ,
		sh:NodeShape
		;
	rdfs:subClassOf ex:ClassC ;
	sh:property [
		a sh:PropertyShape ;
		rdfs:comment "This property shape is OK."@en ;
		sh:maxCount 1 ;
		sh:path ex:propertyP ;
	] ;
	sh:targetClass ex:ClassC ;
	.

ex:ClassE
	a
		owl:Class ,
		sh:NodeShape
		;
	rdfs:subClassOf ex:ClassC ;
	sh:property [
		a sh:PropertyShape ;
		rdfs:comment "This property shape is NOT OK."@en ;
		sh:maxCount 3 ;
		sh:path ex:propertyP ;
	] ;
	sh:targetClass ex:ClassC ;
	.

```

The property shape on `ex:ClassD` is consistent with the demands of its parent `ex:ClassC`.  Requiring a `ex:ClassD` having at most one value for `ex:propertyP` is consistent with `ex:ClassC` having at most two.

The property shape on `ex:ClassE` is *inconsistent* with the demands of its parent `ex:ClassC`.  Requiring a `ex:ClassE` having at most three values for `ex:propertyP` is inconsistent with `ex:ClassC` having at most two.  The SHIR code base would fail the consistency review based on the `sh:maxCount` in `ex:ClassE`'s property shape.

The property shapes on both `ex:ClassD` and `ex:ClassE` *both* make another choice, which is what the SHIR code base will support in its impending release: the class constraint, that objects referenced via `ex:propertyP` must be of class `ex:ClassA`, was omitted.  This is a pattern of delegation to the parent class:  *Some* class in the superclass hierarchy makes a constraint about requiring `ex:ClassA`s, and the subclasses are fine to not repeat that.

In summary, the next release of the SHIR tool is set to continue flagging explicit constraint expansions as the subclass hierarchy is traversed.  But, omission of constraints will no longer be treated as expansions, and further will not be treated as errors.

# Requirements

## Requirement 1

UCO must not require repetition of property constraints from parent class to child class when nothing is changed about the constraint.

## Requirement 2

UCO must adopt a version of SHIR that permits omitting repeated property constraints.

# Risk / Benefit analysis

## Benefits

Some exercises are being performed to test interoperability with UCO and other ontologies.  For instance, [CASE-Corpora](https://github.com/casework/CASE-Corpora/) uses a small, "Zippering" ontology that defines subclasses between the independent class hierarchies of [DCAT v2](https://www.w3.org/TR/vocab-dcat-2/) (and its dependent ontologies and data models, including [Dublin Core Terms](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/)), and [CASE](https://caseontology.org/) & UCO.  That "Zippering" ontology has had to make repetitions of some of the property constraints from parent classes due to demands from review by SHIR.  Unfortunately, the effect of an instance of invalid data becomes multiplied with the class hierarchy's height.  Every violated constraint is reported in the SHACL violations report, even if the constraints are completely redundant with one or more parent classes.  A demonstration of this effect is included in [SHIR PR 12](https://github.com/casework/CASE-Utility-SHACL-Inheritance-Reviewer/pull/12).

Hence, one benefit to having SHIR permit constraint delegation is reduced error output, and the errors that are reported are localized to the shape of the topmost class in the hierarchy imposing the constraint.

There is also a side-benefit of adoption of the next release of SHIR, though this only benefits ontology developers (submitter included) who use UCO's `make`-based workflow.  Some automated Python code review has been put into place to improve testing, and a build artifact created from UCO's local `pip` install is now property ignored by Git.  (Currently, running `make` installs SHIR into a virtual environment as part of CI testing, but a build artifact is generated and flags the submodule as "Dirty."  That is fixed in SHIR's `develop` branch.)

## Risks

Within the scope of UCO, there has been a desire to be explicit on `sh:PropertyShape`s.  That is, repeating each constraint for every `sh:PropertyShape` down the subclass hierarchy has been somewhat seen as a desired feature.  

The submitter believes the benefit of repeated constraints does not outweigh the multiplied messages a user encounters for a violation of a repeated constraint.  Such noise can also mask other data errors, especially if some "Info"- or "Warning"-level violations are set to be accepted for validation but turn out to be operationally significant.

# Competencies demonstrated

The competencies are demonstrated in SHIR pull requests.

## Competency 1

Suppose instance data triggers a property constraint violation in some instance of a subclass C' of a class C.

### Competency Question 1.1

What is the class that originated the violated constraint?

#### Result 1.1

With adoption of the next version of SHIR, a constraint does not need to be repeated.  See [SHIR PR 12](https://github.com/casework/CASE-Utility-SHACL-Inheritance-Reviewer/pull/12), particularly the redundant shapes in [`ex-constraint-repetition.ttl`](https://github.com/casework/CASE-Utility-SHACL-Inheritance-Reviewer/pull/12/files#diff-298532a7bd1e5560727d6cc1da96b9b46d9653137dc097d0eb74421fc08939ad) leading to redundant `sh:ValidationResult`s in [`kb-test-8.ttl`](https://github.com/casework/CASE-Utility-SHACL-Inheritance-Reviewer/pull/12/files#diff-d56ed1d1a32b6a93bd59f6da9797707d81ef5ca8c25ab6995df842b66936b14c).

Before adoption of the next version of SHIR, the `sh:PropertyShape`s of C' and C are both reported in the SHACL validation output.

# Solution suggestion

* Bump SHIR pointer to next release.  Release is planned to be created after this issue passes its Requirements Review vote.

# Coordination

- Tracking in Jira ticket [ONT-474](https://cyberontology.atlassian.net/browse/ONT-474)
- [x] Administrative review completed, proposal announced to Ontology Committees (OCs) on 2022-07-30
- [x] Requirements to be discussed in OC meeting, [2022-08-09](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2030108681/2022-08-09+CDO+Ontology+Committees)
- [x] Requirements Review vote occurred, passing, on 2022-08-09
- [x] *Requirements development phase completed.*
- [x] Solution announced to OCs on 2022-08-12
- [x] Solutions Approval to be discussed in OC meeting, [2022-08-16](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2035023880/2022-08-16+CDO+Ontology+Committees)
- [x] Solutions Approval vote occurred, passing, on 2022-08-25
- [x] *Solutions development phase completed.*
- [x] Implementation [merged](https://github.com/ucoProject/UCO/pull/418) into `develop`
- [x] Milestone linked
- [x] Documentation logged in pending release page

**Comment by ajnelson-nist** [comment]
[PR 418](https://github.com/ucoProject/UCO/pull/418) implements the solution for this proposal.

**Comment by sbarnum** [comment]
I should make a note here that this change will break and require changes to existing code in the form of the UCO Data Platform (UDP) built by MITRE and for planned future open source release to the community. The UDP autogenerates a GraphQL schema and associated API from UCO and UCO-based ontologies. This proposed change will require reworking how the code handles subclass level property shape overrides.

I personally would value the explicit nature of the current approach over limiting edge case repetition of class height validation errors in a specific custom zippering ontology related to but outside UCO.

**Comment by ajnelson-nist** [comment]
Capturing in public comment, re:

> I should make a note here that this change will break and require changes to existing code ...

This Issue and its associated PR does not include removal of redundant property constraints.  It only enables making those redundant constraints optional.

Also, the motivation for that comment was a reliance on UCO's overly-explicit property constraint specification within one tool.  I noted in the OCs meeting on Tuesday that UCO's Data Platform is not the only tool that made use of property constraints.  IIRC, the documentation generator UCO uses may also have made use of all constraints being in a single `sh:PropertyShape`.

Any tool trying to determine all applicable property constraints needs to be aware of the permission in general SHACL to specify those constraints at multiple levels of a RDFS or OWL subclass hierarchy.  So, tools must be prepared to start at a class and look "Up"ward in the hierarchy to determine all applicable constraints.

**Comment by ajnelson-nist** [comment]
The solution for this Issue was provided at the time of the initial Requirements Review opening.  No practical change has taken place in the code base, and its 0.3.0 release has been stamped.  This Issue is now in Solutions Discussion.  A Solutions Approval vote will be held in the Aug 25 meeting.
