### ISSUE TITLE
Suggest removing HasIdentity, HasLocation and RelatedIdentity

### ISSUE THREAD

**Issue by sbarnum** [ucoProject/UCO#42]
To keep the model more simple for now, I would suggest we remove the HasIdentity, HasLocation and RelatedIdentity specializations on Relationship.

**Comment by jstroud-mitre** [comment]
Does this apply to ```Traces ``` as well?

**Comment by sbarnum** [comment]
@jstroud-mitre No. THese are just explicitly defined subclasses of Relationship. 
They are currently specified in core but are not used anywhere.

**Comment by sbarnum** [comment]
Addressed in PR #125

**Comment by sbarnum** [comment]
Resolved in PR #125
