### ISSUE TITLE
Change minCount from 1 to 0 on multiple properties

### ISSUE THREAD

**Issue by eoghanscasey** [ucoProject/UCO#428]
This is proposed as a FastTrack change

# Background

Most properties in UCO are optional. Setting minCount = 1 is enforced by SHACL makes a property required. This constraint will create problems in use cases in which a property is known to have existed but the value is not available.

# Requirements

## Requirement 1
Allow adopters to create an object when the existence of an object is known but an associated property is not known.

# Risk / Benefit analysis
The proposed change allows adopters to decide which property is needed, except when it is ontologically necessary.

## Benefits
Allow adopters to decide which property is needed.

## Risks
The submitter is unaware of risks associated with this change.

# Competencies demonstrated
Adopter creates an object when the existence of an object is known but an associated property is not known.

# Solution suggestion
Change minCount to 0 from 1 on the following properties:

| Class                                       | Property       |
| -----------         | -----------                      |                                             
| identity/AddressFacet                         | identity/address     |           
| observable/AccountFacet                       | observable/accountIdentifier    |
| observable/AlternateDataStreamFacet           | core/name                       |
| observable/ApplicationAccountFacet            | observable/application         | 
| observable/AutonomousSystemFacet              | observable/number           |    
| observable/BluetoothAddressFacet              | observable/addressValue       |  
| observable/ContactAffiliation                 | observable/contactOrganization  |
| observable/ContactListFacet                   | observable/contact              |
| observable/DigitalAddressFacet                | observable/addressValue       |  
| observable/DigitalSignatureInfoFacet          | observable/signatureExists    |  
| observable/DigitalSignatureInfoFacet          | observable/signatureVerified    |
| observable/DomainNameFacet                    | observable/value                |
| observable/EXIFFacet                          | observable/exifData             |
| observable/EmailAccountFacet                  | observable/emailAddress         |
| observable/EmailAddressFacet                  | observable/addressValue         |
| observable/EnvironmentVariable                | core/name                       |
| observable/EventFacet                         | observable/application          |
| observable/GeoLocationEntryFacet              | observable/application          |
| observable/GeoLocationLogFacet                | observable/application          |
| observable/GeoLocationTrackFacet              | observable/application          |
| observable/HTTPConnectionFacet                | observable/requestMethod        |
| observable/HTTPConnectionFacet                | observable/requestValue         |
| observable/IPAddressFacet                     | observable/addressValue         |
| observable/IPv4AddressFacet                   | observable/addressValue         |
| observable/IPv6AddressFacet                   | observable/addressValue         |
| observable/InstantMessagingAddressFacet       | observable/addressValue         |
| observable/MACAddressFacet                    | observable/addressValue         |
| observable/MemoryFacet                        | observable/isInjected           |
| observable/MemoryFacet                        | observable/isMapped             |
| observable/MemoryFacet                        | observable/isProtected          |
| observable/MemoryFacet                        | observable/isVolatile           |
| observable/MessageThreadFacet                 | observable/message              |
| observable/MutexFacet                         | observable/isNamed              |
| observable/OnlineServiceFacet                 | core/name                       |
| observable/PhoneAccountFacet                  | observable/phoneNumber          |
| observable/PropertiesEnumeratedEffectFacet    | observable/properties           |
| observable/SIPAddressFacet                    | observable/addressValue         |
| observable/SendControlCodeEffectFacet         | observable/controlCode          |
| observable/StateChangeEffectFacet             | observable/newObject            |
| observable/SymbolicLinkFacet                  | observable/targetFile           |
| observable/TwitterProfileFacet                | observable/twitterId            |
| observable/URLFacet                           | observable/fullValue            |
| observable/URLHistoryFacet                    | observable/urlHistoryEntry      |
| observable/ValuesEnumeratedEffectFacet        | observable/values               |
| observable/WifiAddressFacet                   | observable/addressValue         |
| observable/WindowsActiveDirectoryAccountFacet | observable/objectGUID          | 
| observable/WindowsPESection                   | core/name                       |
| observable/WindowsRegistryKeyFacet            | observable/key                  |
| observable/WindowsRegistryValue               | core/name                       |
| observable/WindowsServiceFacet                | observable/serviceName          |
| tool/BuildUtilityType                         | tool/buildUtilityName           |
| tool/ConfigurationSettingType                 | tool/itemName                   |
| tool/ConfigurationSettingType                 | tool/itemValue                  |
| tool/DependencyType                           | tool/dependencyDescription      |
| tool/LibraryType                              | tool/libraryName                |
| tool/LibraryType                              | tool/libraryVersion           |

# Coordination

- Tracking in Jira ticket [OC-257](https://unifiedcyberontology.atlassian.net/browse/OC-257)
- [x] Administrative review completed
- [x] Solutions Approval to be discussed in OC meeting, [2022-08-09](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2030108681/2022-08-09+CDO+Ontology+Committees)
- [x] Solutions Approval vote occurred, passing, on 2022-08-09
- [x] *Solutions development phase completed.*
- [x] Implementation has not been merged into `develop`

- [x] Milestone linked
- [x] Documentation logged in pending release page

**Comment by sbarnum** [comment]
It definitely makes sense to make some of these optional to support the ability to express parts of relevant data when not all data is available.
That being said, many of the properties listed here do not make sense to make optional as they are either the only property on the class (which would lead to empty objects) or they simply would not make sense with at least one entry of the property listed.

Here is a list of the properties I do NOT think we should make optional:
![image](https://user-images.githubusercontent.com/2760288/183589981-abe028e5-827e-49e4-9b27-75a4c294f67c.png)

One of the proposed entries lists core:name on observable:AlternateDataStreamFacet. I assume this is intended to mean observable:AlternateDataStream.

**_There is a much bigger apparent issue on the observable:Mutex class.
The mutexName property appears to be missing from the ontology and its property shape missing from the MutexFacet class. I do not know when this happened. A Mutex object is pretty much useless without a mutexName property to convey the mutex. The proposed change to make the isNamed boolean property on the MutexFacet class is fine but meaningless without the mutexName property._**

**Comment by eoghanscasey** [comment]
Sean,

Initially, I had a similar reaction to the minCount being 0 but then recalled the following use cases:

+ A message is recovered from a device but the sender address is not recovered. Therefore, we know a sender address exists but we do not know its value. We want to represent the existence of the node, and motivate further analysis to find and fill in the value. 

+ In a network intrusion, evidence of a staging or C&C node is observed, but not its details (e.g., IP address, FQDN). We want to represent the existence of the node, and motivate further analysis to find and fill in the value. 

For the Mutex gap, can that be fixed with a bug report?

Eoghan Casey

**Comment by sbarnum** [comment]
You can convey the existence of the node using the subclass of ObservableObject (e.g., EmailAccount) without also including an empty instance of the associated facet (e.g., EmailAccountFacet).

Yes, we can and should fix the Mutex gap with a bug report.
