### ISSUE TITLE
Undefined vocabulary:ContactURLScopeVocab-members​

### ISSUE THREAD

**Issue by kchason** [ucoProject/UCO#439]
# Bug description
[observable:ContactURL](https://github.com/ucoProject/UCO/blob/master/ontology/observable/observable.ttl#L1680) defines a SHACL constraint that, for any triple whose subject is a `observable:ContactURL` and whose predicate is observable:contactURLScope​, the value must be (either an `xsd:string`​ or a `vocabulary:ContactURLScopeVocab`​ that is also) an element of `vocabulary:ContactURLScopeVocab-members​`. However, `vocabulary:ContactURLScopeVocab-members​` does not exist.

## Proposed solution
Create a new `vocabulary:ContactURLScopeVocab-members` object similar to the [`vocabulary:ContactSIPScopeVocab-members`](https://github.com/ucoProject/UCO/blob/master/ontology/vocabulary/vocabulary.ttl#L538) and update the `vocabulary:ContactSIPScopeVocab` to point to the new members vocabulary.

**Comment by ajnelson-nist** [comment]
This should already be addressed as part of the resolution of #406.

**Comment by ajnelson-nist** [comment]
@kchason , I believe this was addressed in this specific part of the PR for #406:

https://github.com/ucoProject/UCO/pull/412/files#diff-40c3a2156e9752b255d59875d43a8ab5a94b3080b5df561164764be1d51f979dL1684

Thank you for the report!
