### ISSUE TITLE
What is the distinction between Dictionary and ControlledDictionary?

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#469]
While implementing [Issue 430](https://github.com/ucoProject/UCO/issues/430), I observed `types:Dictionary` and `types:ControlledDictionary` are both parentless classes.  I could not see a reason that `ControlledDictionary` would not be a subclass of `Dictionary`.

The practical difference I see between the two is the corresponding entry class, where `ControlledDictionaryEntry` verbally describes a constraint on a set of values.  There is no implementation of such a constraint.

Is the intent for `ControlledDictionary` to be a disjoint class from `Dictionary`, and likewise for their `Entry` classes?

# Coordination

- Tracking in Jira ticket [OC-22](https://unifiedcyberontology.atlassian.net/browse/OC-22)
- [x] Administrative review completed
- [x] [Implementation](https://github.com/ucoProject/UCO/pull/476) merged into `develop`
- [x] Milestone linked
- [x] Documentation logged in pending release page

**Comment by sbarnum** [comment]
I believe you are correct. I believe ControlledDictionary should be a subclass of Dictionary (and ControlledDictionaryEntry a subclass of DictionaryEntry) as the difference is them is simply a narrowing constraint on the set of values allowed in the types:key property of ControlledDictionaryEntry class.

**Comment by ajnelson-nist** [comment]
I will implement subclassing as a bugfix.

**Comment by ajnelson-nist** [comment]
Once [PR 418](https://github.com/ucoProject/UCO/pull/418) is merged, I'll file a PR to fix this.

**Comment by ajnelson-nist** [comment]
Implementation is being tested in [PR 476](https://github.com/ucoProject/UCO/pull/476).
