### ISSUE TITLE
Add new Event object to uco-investigation

### ISSUE THREAD

**Issue by sbarnum** [ucoProject/UCO#47]
To support broader cyber investigation use cases, we should add a new Event object to uco-investigation.

The Event object would be a direct derivation of uco-core:ContextualCompilation.

It would be defined as "An occurence of some activity characterized by the observables indicating such action occured."

**Comment by sbarnum** [comment]
Event class derived from ContextualCompilation

- eventType(string — controlled vocabulary) (1)
-- Specifies the type of event
-startTime(xsd:datetime) (0..1)
-- Specifies the time that the event started.
- endTime(xsd:datetime) (0..1)
-- Specifies the time that the event ended.
- objects(UcoObject) (0..*)
-- Specifies a reference to an object that is related to this event.
- eventAttribute(DictionaryEntry) (0..*)
-- Specifies attributes of the event. 
-- This is a temporary catch all for other properties until they are deemed worthy of explicit property definition
 
 
DictionaryEntry is a dictionary structure type
- key_name (1)
- For an instance, only one of the following would be present
-- Key_value(literal) (0..1)
-- Object(UcoObject) (0..1)
-- Dictionary(DictionaryEntry) (for nested dictionaries) (0..1)

**Comment by ajnelson-nist** [comment]
Closing as duplicated by #541 .  Implemented in UCO 1.3.0.
