### ISSUE TITLE
NoMagic -- Cannot find 'BasicTypes.uml.xmi'

### ISSUE THREAD

**Issue by packet-rat** [ucoProject/UCO#51]
Get an error when opening the MagicDraw Project in uco/model/uco-1.0-draft.uml.mdzip in MagicDraw v18.5:

"Cannot find the used project 'BasicTypes.uml.xmi'.  Do you want to select it manually?"

![2018-02-25_11-07-26](https://user-images.githubusercontent.com/3220193/36643667-f43a68fc-1a1c-11e8-98b0-1f0824b5dd64.png)

**Comment by packet-rat** [comment]
Note that attempting to use the XMI  file from: 

 https://github.com/STIXProject/specifications/tree/master/uml%20model%20serialization

returns:

![2018-02-25_11-33-41](https://user-images.githubusercontent.com/3220193/36643921-27f83f54-1a20-11e8-9eec-eea8ca2504ec.png)

**Comment by sbarnum** [comment]
The UML model is no longer part of UCO
