### ISSUE TITLE
Failed to create validator: org.topbraid.shacl.validation.SHACLException: Invalid SPARQL constraint

### ISSUE THREAD

**Issue by DrSnowbird** [ucoProject/UCO#513]
# Bug description

Tool transcript:

```
Failed to create validator: org.topbraid.shacl.validation.SHACLException: Invalid SPARQL constraint (Line 5, column 41: Unresolved prefixed name: rdfs:subClassOf):\n\n\t\t\tPREFIX uco-core: <https://ontology.unifiedcyberontology.org/uco/core/>\n\t\t\tSELECT $this\n\t\t\tWHERE {\n\t\t\t        $this a/rdfs:subClassOf* uco-core:UcoThing .\n\t\t\t        FILTER (\n\t\t\t                ! REGEX (\n\t\t\t                        STR($this),\n\t\t\t                        \"[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}$\",\n\t\t\t                        \"i\"\n\t\t\t                )\n\t\t\t        )
```

## Steps to reproduce

Steps to reproduce the behavior.

1. Use Topbraid SHACL validator to load UCO v1.1.0 Shapes and then,
2. Use the input sample: "https://raw.githubusercontent.com/casework/CASE-Examples/master/examples/illustrations/location/location.json"
3. The results will come back to report the failure as "Failed to create validator: org.topbraid.shacl.validation.SHACLException: Invalid SPARQL constraint". -- Please see the attachment JSON file (the response using SHACL validator Service)

[UCO-v1-1-0-SHACL-Exception (copy).txt](https://github.com/ucoProject/UCO/files/10376325/UCO-v1-1-0-SHACL-Exception.copy.txt)

# Coordination

- Tracking in Jira ticket [OC-287](https://unifiedcyberontology.atlassian.net/browse/OC-287)
- [x] Administrative review completed, proposal announced to Ontology Committees (OCs) on 2023-01-17
- [x] Solution announced to OCs on 2023-01-17
- [x] *Solutions development phase completed.*
- [x] [Backwards-compatible implementation](https://github.com/ucoProject/UCO/pull/514) merged into `develop` for the next release
- [x] `develop` state with backwards-compatible implementation [merged](https://github.com/ucoProject/UCO/pull/515) into `develop-2.0.0`
- [x] [Backwards-incompatible implementation](#TODO-link-to-PR) merged into `develop-2.0.0` *(N/A)*
- [x] Milestone linked
- [x] Documentation logged in pending release page

**Comment by ajnelson-nist** [comment]
It appears there's a disagreement between the tool you used and `rdflib` on what the guaranteed RDF prefixes are.  It looks like we need to add explicit `rdfs` declarations to each of the SHACL-SPARQL constraints.

@DrSnowbird , thank you for the bug report, we'll schedule it for the next release.
