### ISSUE TITLE
Unrestrict Cardinality of `observable:IMEI` in `observable:MobileDeviceFacet`

### ISSUE THREAD

**Issue by kchason** [ucoProject/UCO#521]
# Background

Currently, the property [`observable:IMEI`](https://github.com/ucoProject/UCO/blob/master/ontology/uco/observable/observable.ttl#L4483) in the `observable:MobileDeviceFacet` has a max cardinality of 1. This causes issues with devices that contain multiple SIM ports, as each SIM port has its own IMEI. 

In a direct and practical example, a commercial forensics tool (appropriately) identified two IMEIs off the sample mobile device and there's not currently a way to represent this without duplicating a `observable:MobileDeviceFacet` and associating it with the same `observable:Device`.

# Requirements

## Requirement 1

Remove the [`sh:maxCount`](https://github.com/ucoProject/UCO/blob/master/ontology/uco/observable/observable.ttl#L4481) from the `observable:IMEI` property of the `observable:MobileDeviceFacet`. 

# Risk / Benefit analysis

## Benefits

It allows devices that contain multiple SIM cards to be properly represented.

## Risks

There are no known risks to existing adopters since it's loosening restrictions.

# Competencies demonstrated

### Competency Question 1.1

Allow representation of a device with multiple IMEIs.

#### Result 1.1

```json
{
    "@id": "xxxxxx",
    "@type": "observable:MobileDevice",
    "core:hasFacet" {
    	"@id": "xxxxx",
    	"@type": "observable:MobileDeviceFacet",
    	"observable:storageCapacityInBytes": 12345,
    	"observable:IMEI": [
    		"12:ab:34:cd:56:ef:78",
    		"12:ab:34:cd:56:ef:79"
    	]
    }
}
```

# Solution suggestion

```turtle
[
    sh:datatype xsd:string ;
    # sh:maxCount "1"^^xsd:integer ; Remove this property
    sh:nodeKind sh:Literal ;
    sh:path observable:IMEI ;
]
```

# Coordination

- Tracking in Jira ticket [OC-288](https://unifiedcyberontology.atlassian.net/browse/OC-288)

- [x] Administrative review completed, proposal announced to Ontology Committees (OCs) on 2023-02-07
- [x] Requirements to be discussed in OC meeting, [2023-02-23](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2072739842/2023-02-23+Meeting+notes)
- [x] Requirements Review vote occurred, passing, on 2023-02-23
- [x] *Requirements development phase completed.*
- [x] Solution announced to OCs on 2023-03-15
- [x] Solutions Approval to be discussed in OC meeting, [2023-03-23](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2080571398/2023-03-23+CDO+Ontology+Committees+Agenda)
- [x] Solutions Approval vote occurred, passing, on 2023-03-23
- [x] *Solutions development phase completed.*
- [x] [Backwards-compatible implementation](https://github.com/ucoProject/UCO/pull/522) merged into `develop` for the next release
- [x] `develop` state with backwards-compatible implementation [merged](https://github.com/ucoProject/UCO/pull/530) into `develop-2.0.0`
- [x] Backwards-incompatible implementation merged into `develop-2.0.0` (*N/A*)
- [x] Milestone linked
- [x] Documentation logged in pending release page

**Comment by ajnelson-nist** [comment]
Thank you, @kchason !

I looked at how we handled the vote scheduling for MIME type expansion (Change Proposal 104, linked off of the [UCO 0.9.0](https://unifiedcyberontology.org/releases/0.9.0/) release notes).  We did not fast-track that vote.

This hits some of the same potential complexities for interpretation, so we will hold a Requirements Review vote on this one.
