### ISSUE TITLE
Need ability to specify the nature(observed, potential, suggested, imperative, etc) of an action

### ISSUE THREAD

**Issue by Bradichus** [ucoProject/UCO#545]
# Background

**NOTE: Details will be provided soon!**

**Comment by ajnelson-nist** [comment]
Hi, @Bradichus .  Thank you for starting this Issue.  Please email me or @ me in a comment when you have finished its description.  GitHub does not send email notices for edits.

**Comment by Bradichus** [comment]
Hi @ajnelson-nist will do! I am helping out @sbarnum with the ground work of several Change Proposals so expect to see more issues populate today. All descriptions will start the same way 'More details soon' so don't panic haha

**Comment by Bradichus** [comment]
@ajnelson-nist Closing as this is a repeat of #552

**Comment by ajnelson-nist** [comment]
@Bradichus Thank you for the notice.  Please let me know when 552 is ready.  I still see a "more details coming soon" note, so I am assuming for now it is still under construction.
