### ISSUE TITLE
Add optional Origin property to every property bundle

### ISSUE THREAD

**Issue by vikhari** [ucoProject/UCO#56]
**ISSUE FOR VOTE**
_[Deadline: 5/30/18]_

**Vote with a thumbs up or thumbs down (click on the emoji icon in the top right of the post).**

_The following was originally brought up by Harm van Beek._

Add an optional "origin" property to every property bundle that can specify how it was added to the object. Only populate this property when it is added by a separate process or tool.

Use case:
Griffeye is used to review media files, and classifications are added in the form of a property bundle for import into another forensic tool for further analysis.

**Comment by cyberinvestigationexpress** [comment]
Examples of how Hansken data model keeps track of 'origin' include:  extracted, generated, mined, user added. This property could allow any/all possible values, including a specific tool such as 'griffeye'.

**Comment by ajnelson-nist** [comment]
I don't see a reason to "Only populate this property when it is added by a separate process or tool."  I think it should be optional to populate the property by the tool one is currently using.  I'd easily believe some tools wouldn't want to bother, but suppose there is a tool whose main intent is to export its CASE data.  I see no sense demanding the tool leave its name out as it's doing its work.

**Comment by cyberinvestigationexpress** [comment]
CASE bundles typically include which tool was used to process the data, so specifying the tool in this 'origin' property would be repetitive. However, the tool could use this 'origin' property to differentiate between extracted / generated / user added property bundles. It would only be necessary to use a tool name if it is a different tool adding to the data produced by the first tool.

**Comment by ajnelson-nist** [comment]
This issue is now being tracked on UCO Story OC-81.

**Comment by sbarnum** [comment]
Moved into JIRA as OC-81
