### ISSUE TITLE
pattern:PatternExpression is erroneously encoded as a datatype and class

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#562]
# Bug description

The class `pattern:LogicalPattern` constrains the predicate `pattern:patternExpression` to have a "range" of `pattern:PatternExpression` [sic.].

https://github.com/ucoProject/UCO/blob/1.2.0/ontology/uco/pattern/pattern.ttl#L20-L35

```turtle
pattern:LogicalPattern
	a
		owl:Class ,
		sh:NodeShape
		;
	rdfs:subClassOf pattern:Pattern ;
	rdfs:label "LogicalPattern"@en ;
	rdfs:comment "A logical pattern is a grouping of characteristics unique to an informational pattern expressed via a structured pattern expression following the rules of logic."@en ;
	sh:property [
		sh:datatype pattern:PatternExpression ;
		sh:maxCount "1"^^xsd:integer ;
		sh:nodeKind sh:Literal ;
		sh:path pattern:patternExpression ;
	] ;
	sh:targetClass pattern:LogicalPattern ;
	.
```

`pattern:patternExpression` (the predicate) is a `owl:DatatypeProperty`, so it is expected to have a range of some literal.

https://github.com/ucoProject/UCO/blob/1.2.0/ontology/uco/pattern/pattern.ttl#L59-L64

```turtle
pattern:patternExpression
	a owl:DatatypeProperty ;
	rdfs:label "patternExpression"@en ;
	rdfs:comment "An explicit logical pattern expression."@en ;
	rdfs:range pattern:PatternExpression ;
	.
```

But, `pattern:PatternExpression` (capital P) is a `owl:Class`, not `rdfs:Datatype`:

https://github.com/ucoProject/UCO/blob/1.2.0/ontology/uco/pattern/pattern.ttl#L48-L57

```turtle
pattern:PatternExpression
	a
		owl:Class ,
		sh:NodeShape
		;
	rdfs:subClassOf core:UcoInherentCharacterizationThing ;
	rdfs:label "PatternExpression"@en ;
	rdfs:comment "A pattern expression is a grouping of characteristics unique to an explicit logical expression defining a pattern (e.g., regular expression, SQL Select expression, etc.)."@en ;
	sh:targetClass pattern:PatternExpression ;
	.
```

This is an OWL 2 DL error.  Classes cannot be datatypes, and datatype properties cannot have class ranges.

I came across this while trying to figure out how to use `pattern:LogicalPattern` to represent a regular expression substitution command, `s/foo/bar/g`.

To the original drafters of `pattern:Pattern`: How was this supposed to work?  Can somebody please provide a demonstration for that `s/...` regular expression I gave above, from which we can go back and fix `PatternExpression`?

## Steps to reproduce

Please see snippets above.

# Requirements

## Requirement 1

UCO's SHACL constraints must remain consistent with OWL design constraints, particularly around object properties versus datatype (literal-value) properties.  *(This is not a new requirement.)*

## Requirement 2

`pattern:patternExpression` and `pattern:PatternExpression` must be mutually consistent with one another.  Currently, `patternExression` is a datatype property with range `PatternExpression`, but `PatternExpression` is a `owl:Class`, not `rdfs:Datatype`.

# Risk / Benefit analysis

## Benefits

Having `pattern:PatternExpression` established and stable will enable further "downstream" specialization.  See e.g. #550 (under draft).

## Risks

The pattern namespace was not demonstrated before being included in UCO 1.0.0.  If a demonstration is not provided, it will be unclear if freshly-chosen design will be satisfactory.

# Competencies demonstrated

## Competency 1

**Pending demonstration**

### Competency Question 1.1

**Pending demonstration**

#### Result 1.1

**Pending demonstration**

# Solution suggestion

* Change `pattern:patternExpression` to an `owl:ObjectProperty`.
* Change corresponding SHACL constraints around `pattern:patternExpression`.
* Add test to find errant applications of `sh:datatype` attempting to constrain to `owl:Class`es.

# Coordination

- Tracking in Jira ticket [OCUCO-299](https://cyberontology.atlassian.net/browse/OCUCO-299)

- [x] Administrative review completed, proposal announced to Ontology Committees (OCs) on 2023-11-20
- [x] Requirements to be discussed in OC meeting, [2023-11-28](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2116485121/2023-11-28+CDO+Ontology+Committees)
- [x] Requirements Review vote occurred, passing, on 2023-11-28
- [x] *Requirements development phase completed.*
- [x] Solution announced to OCs on 2024-05-01
- [x] Solutions Approval to be discussed in OC meeting, [2024-05-30](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2244804615/)
- [x] Solutions Approval vote occurred, passing, on 2024-05-30
- [x] *Solutions development phase completed.*
- [x] Backwards-compatible implementation merged into `develop` for the next release *(N/A)*
- [x] `develop` state with backwards-compatible implementation merged into `develop-2.0.0` *(N/A)*
- [x] [Backwards-incompatible implementation](https://github.com/ucoProject/UCO/pull/566) merged into `develop-2.0.0`
- [x] Milestone linked
- [x] Documentation [logged](https://github.com/ucoProject/ucoproject.github.io/commit/eced059c67a00f5938e6ef7ed8f1652cc772b7ae) in pending release page
- [x] _Prerelease publication_: CASE `develop` branch updated to track UCO's updated `develop` branch *(N/A)*
- [x] _Prerelease publication_: CASE `develop-2.0.0` branch [updated](https://github.com/casework/CASE/pull/155) to track UCO's updated `develop-2.0.0` branch

**Comment by ajnelson-nist** [comment]
It seems #550 is built on `PatternExpression` being an `owl:Class`.  @sbarnum and/or @Bradichus , do you have input on this issue (562)?  Should `pattern:patternExpression` be an `owl:ObjectProperty`?

**Comment by ajnelson-nist** [comment]
[PR 566](https://github.com/ucoProject/UCO/pull/566) has been filed to address this issue.  The PR includes a test that detects this OWL+SHACL error pattern.  Fortunately, the test only reports this one occurrence.

Note: 566 was written not having seen a demonstration of `PatternExpression`.

**Comment by ajnelson-nist** [comment]
@plbt5 requested in [PR 259 on the CASE website](https://github.com/casework/casework.github.io/pull/259) that the new OWL shape get a description comment.

@plbt5 , how about:

```turtle
uco-owl:sh-datatype-objects-shape
    sh:description "This shape enforces that the sh:datatype constraining predicate does not bind an OWL class for a literal-valued constraint."@en ;
    .
```

**Comment by ajnelson-nist** [comment]
A vote described in the meeting as a Solutions Approval vote was held 2023-11-28, and passed by the attending members.

However, in the email announcement, Jira tracking, and on the GitHub Issue, the pending vote was described to be a Requirements Review vote.

Because the solution is incomplete, I am going to “Split the difference” and consider this to be a passed Requirements Review vote.

The solution can’t be complete until the class being modified receives a demonstration.

**Comment by ajnelson-nist** [comment]
The solution from today's call:

* `pattern:PatternExpression` should be removed/permanently deprecated.
* The datatype constraint on `LogicalPattern` should be set to `xsd:string`.
* The `rdfs:range` on `patternExpression` should be set to `xsd:string`.

**Comment by plbt5** [comment]
Did I request documentation? That's so out of character.

**Comment by plbt5** [comment]
Agree with suggested comment.

**Comment by ajnelson-nist** [comment]
> Agree with suggested comment.

Added, thank you.
