### ISSUE TITLE
`observable:ObservableRelationship` should constrain the types on the objects it is relating

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#573]
# Background

The `observable:ObservableRelationship` class is a subclass of `core:Relationship`.  It currently encodes no specializations or restrictions on `core:Relationship`'s properties.

Informal discussion has noted at times that the `source` and `target` on an `ObservableRelationship` should be observable objects.  On review of the class hierarchy, and in deference to the freedom currently present in `core:Relationship`, it appears they should be `observable:Observable`s, instead of `observable:ObservableObject`s.  (For a diagram of where differences arise between `observable:Observable` and `observable:ObservableObject`, see the "Solution Suggestion" section of [Issue 544](https://github.com/ucoProject/UCO/issues/544).)

# Requirements

## Requirement 1

An object asserted to be an `ObservableRelationship` should require that the objects it is relating (via `core:source` and `core:target`) are `Observable`s.

# Risk / Benefit analysis

## Benefits

* Demonstrates value of creating specializations of core classes, such as `core:Relationship` being specialized by `observable:ObservableRelationship`.
* Encodes an expectation shared by some Ontology Committee members, but not yet formalized.

## Risks

* Removes freedom currently present for users to use an `ObservableRelationship` to relate one thing that is an `Observable` and one thing that isn't.  E.g., say an IT Asset Management system stores a `core:Relationship` between a server and a room, the former typed as an `observable:Computer`, the latter a `location:Location`, with `core:kindOfRelationship` value `Deployed_In`.  **Is it wrong** if this `core:Relationship` is further typed as an `observable:ObservableRelationship`?
   - The resolution of this discussion could relax the proposal to require at least one of `core:source` or `core:target` be an `observable:Observable`.

# Competencies demonstrated

Competencies are omitted from this proposal, as the effects are new restrictions on data, and hence do not enable new expressive abilities.

# Solution suggestion

Add the following to UCO for its next pre-2.0.0 release:

```turtle
observable:ObservableRelationship
	sh:property
		[
			sh:class observable:Observable ;
			sh:message "The source on an ObservableRelationship is expected to be typed as an Observable, and the noted value node is not.  This will be an error in UCO 2.0.0."@en ;
			sh:path core:source ;
			sh:severity sh:Warning ;
		] ,
		[
			sh:class observable:Observable ;
			sh:message "The target on an ObservableRelationship is expected to be typed as an Observable, and the noted value node is not.  This will be an error in UCO 2.0.0."@en ;
			sh:path core:target ;
			sh:severity sh:Warning ;
		]
		;
	.
```

For 2.0.0, reduce that addition to this:

```turtle
observable:ObservableRelationship
	sh:property
		[
			sh:class observable:Observable ;
			sh:path core:source ;
		] ,
		[
			sh:class observable:Observable ;
			sh:path core:target ;
		]
		;
	.
```

# Coordination

- Tracking in Jira ticket [OC-302](https://unifiedcyberontology.atlassian.net/browse/OC-302)
- [x] Administrative review completed, proposal announced to Ontology Committees (OCs) on 2023-12-21
- [x] Requirements to be discussed in OC meeting, [2024-01-18](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2157543426/2024-01-18+CDO+Ontology+Committees)
- [x] Requirements to be discussed in OC meeting, [2024-02-15](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2162688004/2024-02-15+CDO+Ontology+Committees)
- [x] Requirements Review vote occurred, passing, on 2024-02-15
- [x] *Requirements development phase completed.*
- [x] Solution announced to OCs on 2024-03-14
- [x] Solutions Approval to be discussed in OC meeting, [2024-04-25](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2162032648/2024-04-25+CDO+Ontology+Committees)
- [x] Solutions Approval vote occurred, passing, on 2024-04-25
- [x] *Solutions development phase completed.*
- [x] [Backwards-compatible implementation](https://github.com/ucoProject/UCO/pull/574) merged into `develop` for the next release
- [x] `develop` state with backwards-compatible implementation [merged](https://github.com/ucoProject/UCO/pull/601) into `develop-2.0.0`
- [x] [Backwards-incompatible implementation](https://github.com/ucoProject/UCO/pull/575) merged into `develop-2.0.0`
- [x] Milestone linked
- [x] Documentation [logged](https://github.com/ucoProject/ucoproject.github.io/commit/5639bee53cbe628158648d55bacc92a9027ade59) in pending release pages
- [x] _Prerelease publication_: CASE `develop` branch [updated](https://github.com/casework/CASE/pull/151) to track UCO's updated `develop` branch
- [x] _Prerelease publication_: CASE `develop-2.0.0` branch [updated](https://github.com/casework/CASE/pull/152) to track UCO's updated `develop-2.0.0` branch

**Comment by ajnelson-nist** [comment]
The ITAM example I noted under Risks turns out to already have had an analogy hanging around among CASE-Examples.  The Cell Site example uses that pattern - a cell tower `Located_At` a location, and the relationship is an `ObservableRelationship`.  This object got flagged when I merged the PRs for this Issue into the `unstable` test branches:

https://github.com/casework/CASE-Examples/blob/60ba58d/examples/illustrations/cell_site/cell_site.json#L153-L172

**Comment by ajnelson-nist** [comment]
The CASE website had some other examples where just one side of an `ObservableRelationship` is a subclass of `Observable` (links are to today's data):

* https://github.com/casework/casework.github.io/blob/150554f/examples/owl_trafficking/owl_trafficking.json#L1155-L1166 - A `location:Location` `Contained_Within` a `observable:File` .
* https://github.com/casework/casework.github.io/blob/150554f/examples/owl_trafficking/owl_trafficking.json#L380-L391 - A `identity:Person` `Has_Account` a `observable:EmailAccount` .
* https://github.com/casework/casework.github.io/blob/150554f/examples/owl_trafficking/owl_trafficking.json#L392-L403 - A `identity:Person` `Has_Account` a `observable:DigitalAccount` .

**Comment by ajnelson-nist** [comment]
The meeting discussion date has been set to January 18th.

**Comment by sbarnum** [comment]
I agree with the proposal that the constraint should be to observable:Observable rather than observable:ObservableObject.

I believe that the constraint should be that at least one of either source or target should be observable:Observable rather than requiring both be observable:Observable.

**Comment by ajnelson-nist** [comment]
CASE examples have updating PRs posted, which adapt data for the requirements voted on in last month's meeting:

* https://github.com/casework/casework.github.io/pull/283/commits/415428031cf2056150799a4a7a6df73cd1f5a1a3
* https://github.com/casework/CASE-Examples/pull/142/commits/fcfa00b06765422ea9837a4d56ebfea49a1b9954
