### ISSUE TITLE
`observable:AlternateDataStream` is not a subclass of `FileSystemObject`, but `File` and `ReparsePoint` are

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#590]
# Bug description

[These lines](https://github.com/ucoProject/UCO/blob/1.3.0/ontology/uco/observable/observable.ttl#L234-L241) in UCO 1.3.0 designate `AlternateDataStream` as a "top-level" class under `ObservableObject`.  However, the `rdfs:comment` definition scopes the concept to being specific to NTFS files (and hence NTFS file systems).

It seems `AlternateDataStream` should be moved under `observable:FileSystemObject`.

## Steps to reproduce

See disparity between `AlternateDataStream` and, e.g., [`ReparsePoint`](https://github.com/ucoProject/UCO/blob/1.3.0/ontology/uco/observable/observable.ttl#L5825-L5832), another NTFS-specific file system object.

# Coordination

- Tracking in Jira ticket [OC-316](https://unifiedcyberontology.atlassian.net/browse/OC-316)

- [x] Administrative review completed, proposal announced to Ontology Committees (OCs) on 2024-02-08
- [x] *Requirements development phase skipped - proposal fast-tracked.*
- [x] Solution form to be discussed in OC meeting, [2024-02-15](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2162688004)
- [x] Solution announced to OCs on 2024-05-10
- [x] Solutions Approval to be discussed in OC meeting, [2024-05-30](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2244804615/2024-05-30+CDO+Ontology+Committees)
- [x] Solutions Approval vote occurred, passing, on 2024-05-30
- [x] *Solutions development phase completed.*
- [x] [Backwards-compatible implementation](https://github.com/ucoProject/UCO/pull/604) merged into `develop` for the next release
- [x] `develop` state with backwards-compatible implementation [merged](https://github.com/ucoProject/UCO/pull/608) into `develop-2.0.0`
- [x] [Backwards-incompatible implementation](https://github.com/ucoProject/UCO/pull/605) merged into `develop-2.0.0`
- [x] Milestone linked
- [x] Documentation [logged](https://github.com/ucoProject/ucoproject.github.io/commit/a8dffd265a72a119407e79962f8ec3e0608fe781) in pending release page
- [x] _Prerelease publication_: CASE `develop` branch [updated](https://github.com/casework/CASE/pull/153) to track UCO's updated `develop` branch
- [x] _Prerelease publication_: CASE `develop-2.0.0` branch [updated](https://github.com/casework/CASE/pull/155) to track UCO's updated `develop-2.0.0` branch

**Comment by ajnelson-nist** [comment]
I think the right thing to do here is:

* In UCO 2.0.0, change the superclass.
* In UCO 1.4.0, issue a SHACL warning if an `AlternateDataStream` object is not multi-typed as a `FileSystemObject` (i.e., a "soft" notice that the class hierarchy is changing in UCO 2.0.0).

**Comment by sbarnum** [comment]
I concur with this proposal and the suggested approach for 2.0.0 and 1.4.0 in the above comment.

**Comment by ajnelson-nist** [comment]
I intend to handle this as a fast-track proposal.  The ultimate change for UCO 2.0.0 is a 1-liner in the ontology, but we haven't held any votes yet on the "pre-2.0.0 soft warning" style of subclass hierarchy rearrangement that I've put into PR #604 .

**Comment by ajnelson-nist** [comment]
Noting for the sake of review: I tested (for another proposal) whether the documentation build system would render the anonymous shape on the generated class page, when linked by `rdfs:seeAlso`.  It does.

**Comment by ajnelson-nist** [comment]
Noting for today's vote:

Unit tests have been updated, and CI passes, on both attached Pull Requests.

The PRs have not yet run through the [review checklist](https://github.com/Cyber-Domain-Ontology/cdo.github.io/blob/main/CONTRIBUTE.md#pull-request-review) that has often been done before holding a Solutions Approval vote.

The review checklists are in place to catch when there would be effects on any of the examples posted across CASE's example repositories.  At the moment, per [this data-driven list](https://github.com/ajnelson-nist/CASE-Examples-QC/blob/e0ea6514cd84322d58af1e7f581042350d1c3c4d/tests/used_concepts.txt) of ontology concepts used in CASE's examples, there are no instances of `uco-observable:AlternateDataStream`.  So, the review checklist is unlikely to raise any issues.
