### ISSUE TITLE
Remove invalid line from core.ttl

### ISSUE THREAD

**Issue by asovern-mitre** [ucoProject/UCO#62]
Looks like an extra line was added to the core.ttl file accidentally. When present this line makes for an invalid ttl file and causes many errors upon opening in Protege & other RDF tools.

https://github.com/ucoProject/UCO/blob/d43fc13516ee31a8b320fa448c6b2a4df63a5e5d/uco-core/core.ttl#L404

**Comment by asovern-mitre** [comment]
There is also a pending pull request for this same issue from June.
#58

**Comment by cyberinvestigationexpress** [comment]
Removed line in v0.2.1 branch in preparation for merge.
