### ISSUE TITLE
Update Authorization object with start and end time

### ISSUE THREAD

**Issue by cyberinvestigationexpress** [ucoProject/UCO#63]
Some judicial authorizations are restricted to a specific period. This could be represented in the Authorization object with a start and end time.

**Comment by packet-rat** [comment]
Has there been any discussion in this community on temporality (1) in general), (2) representations of same in OWL/RDFS,  and how to deal with higher precision (e.g. extending RDFS Class: | time:TemporalUnit)?

Where would the best place be to engage on this broader topic?

**Comment by sbarnum** [comment]
Addressed in PR #111

**Comment by sbarnum** [comment]
Resolved in PR #111
