### ISSUE TITLE
Line 3131, observable.ttl invalid 

### ISSUE THREAD

**Issue by HamptonJ** [ucoProject/UCO#70]
Line 3131 in the observables.ttl file is missing a double quote.
"Full-size SIM^^xsd:string should be "Full-size SIM"^^xsd:string.
This is in the turtle-cleanup branch, @sbarnum

**Comment by sbarnum** [comment]
Resolved in commit 07a5c2fef75e01d7b523b2364a3ed2c70b3d54d8
