### ISSUE TITLE
Another Punning issue caused by ObjectProperty and DataProperty with same name.

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#83]
![PunningIssue](https://user-images.githubusercontent.com/9854293/57262666-f51c1200-7021-11e9-8867-87fe9c101d1f.png)

Another and hopefully the last of the punning issues.

**Comment by rhohimer** [comment]
It appears to me that the ObjectProperty predicates involved here are intended to point to objects of type CyberItem. To resolve this issue for now the ObjectProperty name will be appended with "Object" such as:
phoneNumberObject . This will resolve the name conflict between DataProperties and ObjectProperties.

**Comment by rhohimer** [comment]
Punning errors where ObjectProperties and DataProperties have a collision will need to be fixed...

**Comment by rhohimer** [comment]
Per discussion with @sbarnum the punning errors due to ObjectProperty and DataProperty name collisions will be addressed at a later date. My proposal to append "Object" or "Obj" to the ObjectProperty name will be considered to remove that ambiguity.

**Comment by sbarnum** [comment]
phoneNumber
* Solution: rename the ObjectProperty to just “phone"
Password
* Solution: remove ObjectProperty and make “password" on URL just a string
values
* Solution: Change ObjectProperty name to “registryValues"
Domain
* Solution: Change ObjectProperty to “cookieDomain"
Creator
* Solution: Change DatatypeProperty to be “taskCreator"
messageID
* Solution: The ObjectProperty is an error. Both uses should just be a string

**Comment by rhohimer** [comment]
![image](https://user-images.githubusercontent.com/9854293/60825784-57e47380-a161-11e9-810a-be388e3764f4.png)

@sbarnum  I see you have assigned yourself to this one, but we'd be happy to knock it out per your suggested solutions.

**Comment by sbarnum** [comment]
Fine by me. :-)

**Comment by rhohimer** [comment]
phoneNumber
Done: renamed the ObjectProperty to “phone"

password
Done: remove ObjectProperty and make “password" on URL just a string

values
Done: Changed ObjectProperty name to “registryValues"

domain
Done: Changed ObjectProperty to “cookieDomain"

creator
Done: Changed DatatypeProperty to be “taskCreator"

messageID
Done: Deleted the ObjectProperty "messageID"

**Comment by sbarnum** [comment]
@rhohimer Are you still working this one or would it make sense for me to quickly implement changes in a branch?
