### ISSUE TITLE
There is ambiguity due to multiple ObjectProperties called "object" in three different namespaces core, types, and action.

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#84]
![objext-ambiguity](https://user-images.githubusercontent.com/9854293/57316239-2d673300-70aa-11e9-9ef8-d026999047d0.png)

**Comment by rhohimer** [comment]
fixed in a branch to be merged with turtle-cleanup branch.

**Comment by sbarnum** [comment]
types:object should not be an issue as it should be removed with issue #114

**Comment by sbarnum** [comment]
I do not believe that there is any ambiguity between core:object, action:object, observable:oldObject and observable:newObject.

Each of these four properties have clearly defined and distinct semantics as specified in the definition comments.

core:object is explicitly defined as one or more UcoObjects. It is a general property for representing other UCO objects without any constraints on what types of UCO Objects may be used which is necessary in many use cases. Here the name "object" clearly denotes the concept of some atomic representation of something.

action:object is explicitly defined as "The things that the action is performed on/against." This is both a clearly different semantic meaning of the name "object" than is used in core:object. Here it is referring to the grammatical use of the term where any particular action has a subject that performs the action, a verb characterizing the actual action and an object that the action acts on. This clear distinction is made in the definition.

Further, there should be no ambiguity of confusion between core:object and action:object as they are each defined in separate namespaces that will clearly separate and denote the individual semantics of each from the other. This is one of many examples of why such namespaces are relevant and necessary.

The observable:oldObject and observable:newObject should have no ambiguity or confusion with core:object or action:object as even their property names are clearly distinct. They are also defined in a separate namespace to clearly delineate them from the others. Lastly, they are explicitly defined with clear meaning in the property definitions to represent CyberItem object state before and after some state change occurs.

From everything I can see these four properties:

- have clearly valid and distinct use cases (semantic meanings)
- are explicitly and clearly defined to convey their intended meanings
- are correctly segregated into their own context-specific namespaces to deconflict with other uses

**Comment by rhohimer** [comment]
Technically, because they are in separate and distinct namespaces, you have removed the collision. However, you have two semantic meanings associated with the ObjectProperty "object".  Programmatically, there is no ambiguity, computers do exactly what they are told.  There is ambiguity for human authors and readers. If they accidently use the wrong namespace, the computer will use the incorrect typing to made incorrect inferences. Garbage in, garbage out.

I consider this as a difference in modeling styles and practices. You are technically correct and computers will not see any ambiguity. Humans, on the other hand, make mistakes, when there are different senses of a word to choose from.

A separate issue, but related to the types:object is:

![image](https://user-images.githubusercontent.com/9854293/60982900-db32d000-a2ed-11e9-958a-39f9b8d932fc.png)

We should review the use of types:object on the ArrayOfObject. It violates the range setting of UcoObject by pointing to an owl:Thing.

![image](https://user-images.githubusercontent.com/9854293/60983300-8fccf180-a2ee-11e9-97a9-39114f592a2c.png)

**Comment by sbarnum** [comment]
ArrayOfObject and types:object issue should be addressed in PR #114

**Comment by sbarnum** [comment]
Resolved in PR #120
