### ISSUE TITLE
Item and CyberItem, Action and CyberAction, need to be subclassed properly

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#86]

**Comment by rhohimer** [comment]
![ItemActionIssues](https://user-images.githubusercontent.com/9854293/57341302-b738ef80-70ee-11e9-8070-67fa1d311167.png)

**Comment by packet-rat** [comment]
Aren't “Action” and “CyberAction” completely different concepts and contexts?

Patrick Maroney

**Comment by rhohimer** [comment]
CyberAction is a subclass of Action and Observable. A CyberAction is everything an Action is, plus its "cyber" parts.

**Comment by packet-rat** [comment]
Disregard -- Testing GitHub <> Slack

**Comment by rhohimer** [comment]
Adding the subclass of CyberAction to Action is straightforward. However, since Action is defined in the action.ttl and CyberAction is defined in observable.ttl, I think the proper location to make the assertion is in uco.ttl which imports both. This is different from the method used to subclass CyberRelationship.

**Comment by rhohimer** [comment]
This bug issue is still pending due to a forced push back to March 26 commit.

**Comment by rhohimer** [comment]
Subclassed CyberItem to Item
Subclassed CyberAction to Action
Both in exactly the same way as CyberRelationship to Relationship.
