### ISSUE TITLE
Hash Should be a Subclass of Facet

### ISSUE THREAD

**Issue by HamptonJ** [ucoProject/UCO#89]
![image](https://user-images.githubusercontent.com/29240333/57492195-cc3f8b00-7274-11e9-99a8-cb683f35b281.png)

**Comment by rhohimer** [comment]
This is being fixed in the turtle-cleanup branch.

**Comment by rhohimer** [comment]
The current UCO model has a **Facet** subclass of **ContentData**. **ContentData** is set as the domain of the **_hash_** predicate which has **Hash** set as the range. **Hash** has the **_hasValue_** and the **_hasMethod_** predicates.  **Hash** is by design not a subclass of **Facet**
