### ISSUE TITLE
types:hashMethod and observable:HashNameEnum seem to be unrelated

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#95]
As of today's master branch (`cc1ba30`), I don't see a way to relate the hash name enumeration in `observable.ttl` to `types:hashMethod`.

Would it be appropriate to replace:
`types:hashMethod rdfs:range xsd:string`
with:
`types:hashMethod rdfs:range observable:HashNameEnum`
?

**Comment by ajnelson-nist** [comment]
This also seems to be true in today's turtle-cleanup head (`c494954`).

**Comment by rhohimer** [comment]
@ajnelson-nist , I'll look into this today. This is an issue that I have been thinking about. It is possible to assert a statement that allows a value not in the enumeration. If a reasoner is run, it will flag a logical inconsistency if the value is not in the enumeration. Applications running description logics reasoners can check for logical consistency. However, a HUMAN authoring an assertion with a value not in the enumeration will not be warned.

**Comment by sbarnum** [comment]
Reworking how we have defined open vocabularies is one of the things I have on my list that we need to do once we get things cleaned up and have a chance.
FireEye has an approach that has proven successful that I think we should leverage.
I will enter a ticket for it when I have a chance.

**Comment by rhohimer** [comment]
![HashNameEnum-Range](https://user-images.githubusercontent.com/9854293/58902894-f55b0c00-86b8-11e9-86b0-a0d50928af69.png)
![InferredHash](https://user-images.githubusercontent.com/9854293/58902895-f55b0c00-86b8-11e9-9683-bb6aade774d8.png)
![HashInconsistent](https://user-images.githubusercontent.com/9854293/58902896-f5f3a280-86b8-11e9-9053-8008c0d29028.png)

The range on hasMethod is not currently set to HashNameEnum.  Until the refactor that Sean mentioned is done, the range on hasMethod should be changed the HashNameEnum in my opinion.

**Comment by sbarnum** [comment]
Addressed in PR #109

**Comment by sbarnum** [comment]
Resolved in PR #109
