### ISSUE TITLE
Usage of triple-quotes not preserved in rdf-toolkit round trip

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#96]
I've used rdf-toolkit (with [this script](https://gist.github.com/ajnelson-nist/53a7c2772747a821f7798e93aaf78cc2)) to test round-trip conversions between Turtle and RDF-XML.  I've found that triple-quotes do not survive a round-trip between Turtle, RDF-XML, and back.  They are preserved converting Turtle-to-Turtle (e.g. for formatting normalization), but not preserved converting RDF-XML-to-Turtle.

In some cases, triple-quote characters allow multi-line strings to be used, such as in the `rdfs:comment` for `observable:Library`.  The round trip preserves that usage of triple-quotes.  However, where a triple-quote is unnecessary, the round trip converts those to single-`"` wrapped strings.

I suggest single quotation mark characters (`"`) be used to wrap strings that don't require multiple lines, to avoid inconsequential diffs in the future.

(Separately, I've noticed most of these multi-line comments appear to be TODO-style jottings.)

**Comment by rhohimer** [comment]
Nice observation @ajnelson-nist ! I noticed this when testing the _round trip_ as well. But I did not get to the diagnostic depth you did. I am going to be changing the change request to limit the normalization to Turtle-to-Turtle for reasons other than this issue.

Do you think there is more to this issue to discuss and keep the issue open? If so, good deal. If not, I'll close the issue.

**Comment by ajnelson-nist** [comment]
If we decide to not support normalization that survives a Turtle-XML-Turtle round trip, then there is no further action to be taken on this issue.

However, I hope it is clear that the first time somebody uses an ontology tool that is RDF-XML oriented, this triple-quote issue will come up again.  How likely this is, I don't know.

I personally think it would be better to just have someone crank through the files and de-triplicate quotes now, because it's not a lot of mental energy to do, and it would avert having to revisit this issue later.  I wouldn't mind doing it, if you would be fine with a Pull Request coming to the `turtle-cleanup` branch.

**Comment by rhohimer** [comment]
We are in agreement @ajnelson-nist .  Fortunately for me, Protege reads the turtle, internally converts to rdf-xml, then saves as turtle, without issue from the triplicate quotes. But, a simple solution is the de-triplicate quotes. I'll leave this issue open until we form a path forward.

**Comment by ajnelson-nist** [comment]
For reference, the `CASE-Examples-QC` change that helped me find the triple quotes is here:
https://github.com/ajnelson-nist/CASE-Examples-QC/commit/541b405e0a90bd221fa0c47ae5988a87768137c9

**Comment by ajnelson-nist** [comment]
For reference, the `CASE-Examples-QC` change that helped me find the triple quotes is here:
https://github.com/ajnelson-nist/CASE-Examples-QC/commit/541b405e0a90bd221fa0c47ae5988a87768137c9

**Comment by sbarnum** [comment]
Addressed in commit d0fb0ba7d281060ce47817a956523e25b9093ca8

**Comment by sbarnum** [comment]
Fixed in https://github.com/ucoProject/UCO/releases/tag/0.4.0
